<?php
defined( 'ABSPATH' ) || exit;

/**
 * Noki UI translation layer.
 * Translates fixed theme copy that lives in PHP templates while keeping
 * editorial content in Polylang translation posts.
 */
function noki_ui_translations() {
	$manual = [
		'zh' => [
			'Who We Are'=>'关于我们','About Noki'=>'关于 Noki','A logistics partner you can count on'=>'值得信赖的物流合作伙伴',
			'10+ years moving cargo across East Africa with reliability, transparency and care.'=>'十余年来，我们以可靠、透明和用心的服务运输东非货物。',
			'Our story'=>'我们的故事','Company'=>'公司','Why Choose Us'=>'为何选择我们','What sets us apart'=>'我们的优势','Our Team'=>'我们的团队','The people behind Noki'=>'Noki 背后的团队',
			'Join Us'=>'加入我们','Careers & openings'=>'职业机会与职位','Resources'=>'资源','Pricing'=>'价格','Clear, fair rates'=>'清晰、公平的价格','Testimonials'=>'客户评价','What clients say'=>'客户怎么说','FAQ'=>'常见问题','Common questions'=>'常见问题',
			'Services'=>'服务','End-to-end supply chain, handled with precision'=>'精准管理端到端供应链','Air, sea and road freight plus customs and warehousing — one trusted partner across East Africa.'=>'空运、海运、公路运输、清关和仓储——一个值得信赖的东非物流伙伴。',
			'Get a quote'=>'获取报价','Freight'=>'货运','Logistics'=>'物流','Reliable & insured'=>'可靠并有保险','Fast & secure'=>'快速且安全','Contact'=>'联系我们','Call us anytime'=>'随时致电我们','Get a Quote'=>'获取报价',
			'Moving your cargo further, faster & safer'=>'让您的货物运得更远、更快、更安全','Trusted freight partner across East Africa'=>'东非值得信赖的货运伙伴','From Kampala to the world — air, sea and road freight, customs clearance and warehousing you can rely on.'=>'从坎帕拉到全球——可靠的空运、海运、公路运输、清关和仓储服务。',
			'Global reach, local expertise'=>'全球网络，本地专业','One trusted partner for your entire supply chain — across East Africa and beyond.'=>'一个值得信赖的合作伙伴，覆盖东非及全球的整个供应链。',
			'Cross-border specialists'=>'跨境运输专家','Reliable delivery across East Africa'=>'东非可靠配送','Kenya, Tanzania, Rwanda, DRC and South Sudan — on time, every time.'=>'肯尼亚、坦桑尼亚、卢旺达、刚果（金）和南苏丹——始终准时。',
			'Our growing road fleet'=>'不断扩大的公路运输车队','Capacity to Move East Africa'=>'运输东非的强大能力','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics 拥有车队、专业团队和区域经验，可在乌干达及整个东非可靠运输商业货物。',
			'Get a Free Quote'=>'获取免费报价','Explore Services'=>'查看服务','Our Services'=>'我们的服务','Contact Us'=>'联系我们','Road Transport'=>'公路运输','Proudly moving goods for businesses of every size'=>'自豪地为各种规模的企业运输货物',
			'Who we are'=>'关于我们','What we offer'=>'我们的服务','How we can help you move'=>'我们如何帮助您运输','All Services'=>'全部服务','Learn more'=>'了解更多','Why Noki'=>'为何选择 Noki',
			"Built for businesses that can't afford delays"=>'为不能承受延误的企业而打造','Delivering goods reliably'=>'可靠交付货物','Cutting-edge tracking'=>'先进货物追踪','Personalised service'=>'个性化服务',
			'Special highlights'=>'特别亮点','Discover Noki Logistics!'=>'发现 Noki Logistics！','View All News'=>'查看全部新闻','Read more'=>'阅读更多','Success hinges on collaboration'=>'成功源于协作','Your goods, handled like our own'=>'像对待自己的货物一样用心',
			'Door-to-door coordination'=>'门到门协调','One point of contact for the entire journey.'=>'全程一个联系人。','Customs expertise'=>'清关专业能力','Licensed clearing agents who know URA inside-out.'=>'熟悉 URA 流程的持证清关代理。',
			'Transparent pricing'=>'透明定价','Clear quotes upfront — what we say is what you pay.'=>'提前提供清晰报价——所报即所付。','Latest updates'=>'最新动态','From Noki Logistics on LinkedIn'=>'Noki Logistics 的 LinkedIn 动态',
			'Fleet updates, regional operations, company news and insights from our team.'=>'车队更新、区域运营、公司新闻及团队洞察。','View on LinkedIn'=>'在 LinkedIn 查看','Follow Noki Logistics on LinkedIn'=>'在 LinkedIn 关注 Noki Logistics','See our latest fleet updates, regional operations and company news.'=>'查看我们的最新车队动态、区域运营和公司新闻。',
			'Client stories'=>'客户故事','Our values'=>'我们的价值观','Insights'=>'洞察','From our logistics blog'=>'来自我们的物流博客','All Articles'=>'全部文章','Read article'=>'阅读文章','Ready when you are'=>'随时为您服务','Chat on WhatsApp'=>'WhatsApp 咨询',
			'About Noki Logistics'=>'关于 Noki Logistics','Home'=>'首页','About Us'=>'关于我们','Years of excellence'=>'多年卓越服务','Our mission & values'=>'我们的使命与价值观','What drives us'=>'我们的动力','Work With Us'=>'与我们合作',
			"Let's move your business forward"=>'让我们推动您的业务向前','Get in touch today for a free logistics consultation and quote.'=>'立即联系我们，获取免费的物流咨询和报价。','View Services'=>'查看服务',
			"Let's talk about your shipment"=>'让我们聊聊您的货运需求','Visit our office'=>'访问我们的办公室','Call or WhatsApp'=>'电话或 WhatsApp','Working hours'=>'工作时间','Emergency line: 24/7'=>'紧急热线：24/7','Get a free quote'=>'获取免费报价',
			'Our Team'=>'我们的团队','Behind every shipment'=>'每票货物背后的团队','Experienced people who care'=>'经验丰富且用心的团队','Our culture'=>'我们的文化','One team, one promise'=>'一个团队，一个承诺','Join Our Team'=>'加入我们的团队','Work with a team that delivers'=>'与真正能交付的团队合作',
			'Clear, fair pricing'=>'清晰、公平的定价','How pricing works'=>'定价方式','No hidden fees, ever'=>'绝无隐藏费用','Questions'=>'常见问题','Pricing FAQs'=>'价格常见问题','Get your custom quote'=>'获取专属报价','Request a Quote'=>'申请报价','WhatsApp Us'=>'WhatsApp 联系我们',
			'Trusted across East Africa'=>'深受东非客户信赖','Real results, real businesses'=>'真实成果，真实企业','Join hundreds of happy shippers'=>'加入数百家满意客户','Experience logistics you can actually rely on. Get your free quote today.'=>'体验真正可靠的物流服务。立即获取免费报价。',
			'Why businesses choose Noki'=>'企业为何选择 Noki','The Noki difference'=>'Noki 的不同之处','Logistics that works the way you do'=>'契合您业务方式的物流服务','On-time, every time'=>'每次都准时','Dedicated coordinator'=>'专属协调员','Regional reach'=>'区域覆盖','Fully insured cargo'=>'货物全程保险','How it works'=>'服务流程','Simple, from quote to delivery'=>'从报价到交付，简单透明','Start a Shipment'=>'开始发货','See the difference for yourself'=>'亲自体验不同',
			'Logistics Blog'=>'物流博客','No posts yet'=>'暂无文章','Check back soon — we’re working on more logistics insights.'=>'请稍后再来——我们正在准备更多物流洞察。','Our Services'=>'我们的服务','End-to-end logistics'=>'端到端物流','Freight solutions for every need'=>'满足各种需求的货运方案','Not sure which service you need?'=>'不确定需要哪项服务？','Speak to an Expert'=>'咨询专家',
			'Service'=>'服务','Key features'=>'主要特点','Need this service?'=>'需要这项服务？','All services'=>'全部服务','Get a free quote'=>'获取免费报价','Talk to us'=>'联系我们','WhatsApp Chat'=>'WhatsApp 咨询',
			'Stay in the loop'=>'掌握最新动态','News & Events'=>'新闻与活动','Back to News & Events'=>'返回新闻与活动','Latest news'=>'最新新闻','More news coming soon.'=>'更多新闻即将发布。','Need to ship something?'=>'需要运输货物吗？','Recent articles'=>'最新文章','Need a quote?'=>'需要报价？',
			'Page Not Found'=>'页面未找到',"Sorry, the page you're looking for doesn't exist or has been moved."=>'抱歉，您查找的页面不存在或已被移动。','Back to Home'=>'返回首页',
			'Your trusted partner for efficient, reliable freight and supply-chain solutions across Uganda and East Africa. Air, sea and road — delivered with speed and care.'=>'您在乌干达和东非值得信赖的高效、可靠货运与供应链合作伙伴。空运、海运和公路运输——快速且用心地交付。',
			'Get in touch'=>'联系我们','Subscribe for logistics tips & updates.'=>'订阅物流技巧与最新动态。','Your email address'=>'您的电子邮箱','All rights reserved.'=>'版权所有。','Privacy Policy'=>'隐私政策','Terms of Service'=>'服务条款'
		],
		'fr' => [
			'Who We Are'=>'Qui sommes-nous','About Noki'=>'À propos de Noki','A logistics partner you can count on'=>'Un partenaire logistique sur lequel vous pouvez compter','Our story'=>'Notre histoire','Company'=>'Entreprise','Why Choose Us'=>'Pourquoi nous choisir','What sets us apart'=>'Ce qui nous distingue','Our Team'=>'Notre équipe','The people behind Noki'=>'Les personnes derrière Noki','Join Us'=>'Rejoignez-nous','Careers & openings'=>'Carrières et postes','Resources'=>'Ressources','Pricing'=>'Tarifs','Clear, fair rates'=>'Des tarifs clairs et équitables','Testimonials'=>'Témoignages','What clients say'=>'Ce que disent nos clients','FAQ'=>'FAQ','Common questions'=>'Questions fréquentes','Services'=>'Services','Get a quote'=>'Demander un devis','Freight'=>'Fret','Logistics'=>'Logistique','Reliable & insured'=>'Fiable et assuré','Fast & secure'=>'Rapide et sécurisé','Contact'=>'Contact','Call us anytime'=>'Appelez-nous à tout moment','Get a Quote'=>'Demander un devis',
			'Trusted freight partner across East Africa'=>'Partenaire fret de confiance en Afrique de l’Est','Global reach, local expertise'=>'Portée mondiale, expertise locale','Cross-border specialists'=>'Spécialistes du transfrontalier','Our growing road fleet'=>'Notre flotte routière en croissance','Capacity to Move East Africa'=>'La capacité de faire avancer l’Afrique de l’Est','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics dispose de la flotte, des équipes et de l’expérience régionale nécessaires pour transporter de manière fiable des marchandises commerciales en Ouganda et en Afrique de l’Est.',
			'Get a Free Quote'=>'Obtenir un devis gratuit','Explore Services'=>'Découvrir nos services','Our Services'=>'Nos services','Contact Us'=>'Nous contacter','Road Transport'=>'Transport routier','Who we are'=>'Qui sommes-nous','What we offer'=>'Ce que nous proposons','How we can help you move'=>'Comment nous pouvons vous aider à transporter','All Services'=>'Tous les services','Learn more'=>'En savoir plus','Why Noki'=>'Pourquoi Noki',"Built for businesses that can't afford delays"=>'Conçu pour les entreprises qui ne peuvent pas se permettre de retards','Delivering goods reliably'=>'Livraison fiable des marchandises','Cutting-edge tracking'=>'Suivi de pointe','Personalised service'=>'Service personnalisé',
			'Special highlights'=>'À la une','Discover Noki Logistics!'=>'Découvrez Noki Logistics !','View All News'=>'Voir toutes les actualités','Read more'=>'Lire la suite','Transparent pricing'=>'Tarification transparente','Latest updates'=>'Dernières nouvelles','From Noki Logistics on LinkedIn'=>'Noki Logistics sur LinkedIn','View on LinkedIn'=>'Voir sur LinkedIn','Follow Noki Logistics on LinkedIn'=>'Suivre Noki Logistics sur LinkedIn','Client stories'=>'Témoignages clients','Our values'=>'Nos valeurs','Insights'=>'Conseils','From our logistics blog'=>'Sur notre blog logistique','All Articles'=>'Tous les articles','Read article'=>'Lire l’article','Ready when you are'=>'Prêts quand vous l’êtes','Chat on WhatsApp'=>'Discuter sur WhatsApp',
			'About Noki Logistics'=>'À propos de Noki Logistics','Home'=>'Accueil','About Us'=>'À propos','Years of excellence'=>'Années d’excellence','Our mission & values'=>'Notre mission et nos valeurs','What drives us'=>'Ce qui nous motive','Work With Us'=>'Travaillez avec nous',"Let's move your business forward"=>'Faisons avancer votre entreprise','View Services'=>'Voir les services',
			"Let's talk about your shipment"=>'Parlons de votre expédition','Visit our office'=>'Visitez nos bureaux','Call or WhatsApp'=>'Appelez ou WhatsApp','Working hours'=>'Horaires','Emergency line: 24/7'=>'Ligne d’urgence : 24/7','Get a free quote'=>'Obtenir un devis gratuit',
			'Behind every shipment'=>'Derrière chaque expédition','Experienced people who care'=>'Des professionnels expérimentés et attentifs','Our culture'=>'Notre culture','One team, one promise'=>'Une équipe, une promesse','Join Our Team'=>'Rejoignez notre équipe','Work with a team that delivers'=>'Travaillez avec une équipe qui tient ses engagements',
			'How pricing works'=>'Comment fonctionnent nos tarifs','No hidden fees, ever'=>'Aucun frais caché','Questions'=>'Questions','Pricing FAQs'=>'FAQ sur les tarifs','Get your custom quote'=>'Obtenez votre devis personnalisé','Request a Quote'=>'Demander un devis','WhatsApp Us'=>'Nous écrire sur WhatsApp',
			'Trusted across East Africa'=>'La confiance partout en Afrique de l’Est','Real results, real businesses'=>'Des résultats réels pour de vraies entreprises','Join hundreds of happy shippers'=>'Rejoignez des centaines de clients satisfaits','Why businesses choose Noki'=>'Pourquoi les entreprises choisissent Noki','The Noki difference'=>'La différence Noki','Logistics that works the way you do'=>'Une logistique adaptée à votre façon de travailler','On-time, every time'=>'Toujours à l’heure','Dedicated coordinator'=>'Coordinateur dédié','Regional reach'=>'Couverture régionale','Fully insured cargo'=>'Marchandises entièrement assurées','How it works'=>'Comment ça marche','Simple, from quote to delivery'=>'Simple, du devis à la livraison','Start a Shipment'=>'Démarrer une expédition','See the difference for yourself'=>'Voyez la différence par vous-même',
			'Logistics Blog'=>'Blog logistique','No posts yet'=>'Aucun article pour le moment','Our Services'=>'Nos services','End-to-end logistics'=>'Logistique de bout en bout','Freight solutions for every need'=>'Des solutions de fret pour chaque besoin','Not sure which service you need?'=>'Vous ne savez pas quel service choisir ?','Speak to an Expert'=>'Parler à un expert','Service'=>'Service','Key features'=>'Caractéristiques principales','Need this service?'=>'Besoin de ce service ?','All services'=>'Tous les services','Talk to us'=>'Parlez-nous','WhatsApp Chat'=>'Chat WhatsApp','Stay in the loop'=>'Restez informé','News & Events'=>'Actualités et événements','Back to News & Events'=>'Retour aux actualités','Latest news'=>'Dernières actualités','More news coming soon.'=>'Plus d’actualités bientôt.','Need to ship something?'=>'Vous avez quelque chose à expédier ?','Recent articles'=>'Articles récents','Need a quote?'=>'Besoin d’un devis ?',
			'Page Not Found'=>'Page introuvable',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Désolé, la page que vous recherchez n’existe pas ou a été déplacée.','Back to Home'=>'Retour à l’accueil','Get in touch'=>'Nous contacter','Subscribe for logistics tips & updates.'=>'Abonnez-vous à nos conseils et actualités logistiques.','Your email address'=>'Votre adresse e-mail','All rights reserved.'=>'Tous droits réservés.','Privacy Policy'=>'Politique de confidentialité','Terms of Service'=>'Conditions d’utilisation'
		],
		'de' => [
			'Who We Are'=>'Über uns','About Noki'=>'Über Noki','A logistics partner you can count on'=>'Ein Logistikpartner, auf den Sie zählen können','Our story'=>'Unsere Geschichte','Company'=>'Unternehmen','Why Choose Us'=>'Warum Noki','What sets us apart'=>'Was uns auszeichnet','Our Team'=>'Unser Team','The people behind Noki'=>'Die Menschen hinter Noki','Join Us'=>'Karriere','Careers & openings'=>'Karriere & Stellen','Resources'=>'Ressourcen','Pricing'=>'Preise','Clear, fair rates'=>'Klare, faire Preise','Testimonials'=>'Kundenstimmen','What clients say'=>'Was unsere Kunden sagen','FAQ'=>'FAQ','Common questions'=>'Häufige Fragen','Services'=>'Leistungen','Get a quote'=>'Angebot anfordern','Freight'=>'Fracht','Logistics'=>'Logistik','Reliable & insured'=>'Zuverlässig & versichert','Fast & secure'=>'Schnell & sicher','Contact'=>'Kontakt','Call us anytime'=>'Rufen Sie uns jederzeit an','Get a Quote'=>'Angebot anfordern',
			'Trusted freight partner across East Africa'=>'Verlässlicher Frachtpartner in Ostafrika','Global reach, local expertise'=>'Globale Reichweite, lokale Expertise','Cross-border specialists'=>'Spezialisten für grenzüberschreitende Transporte','Our growing road fleet'=>'Unsere wachsende Lkw-Flotte','Capacity to Move East Africa'=>'Kapazität, Ostafrika zu bewegen','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics verfügt über die Flotte, das Team und die regionale Erfahrung, um kommerzielle Fracht zuverlässig in Uganda und Ostafrika zu transportieren.',
			'Get a Free Quote'=>'Kostenloses Angebot','Explore Services'=>'Leistungen entdecken','Our Services'=>'Unsere Leistungen','Contact Us'=>'Kontaktieren Sie uns','Road Transport'=>'Straßentransport','Who we are'=>'Über uns','What we offer'=>'Was wir bieten','How we can help you move'=>'Wie wir Ihre Fracht bewegen','All Services'=>'Alle Leistungen','Learn more'=>'Mehr erfahren','Why Noki'=>'Warum Noki',"Built for businesses that can't afford delays"=>'Für Unternehmen, die sich Verzögerungen nicht leisten können','Delivering goods reliably'=>'Zuverlässige Lieferung','Cutting-edge tracking'=>'Modernes Tracking','Personalised service'=>'Persönlicher Service',
			'Special highlights'=>'Highlights','Discover Noki Logistics!'=>'Entdecken Sie Noki Logistics!','View All News'=>'Alle Neuigkeiten','Read more'=>'Weiterlesen','Transparent pricing'=>'Transparente Preise','Latest updates'=>'Neueste Updates','From Noki Logistics on LinkedIn'=>'Noki Logistics auf LinkedIn','View on LinkedIn'=>'Auf LinkedIn ansehen','Follow Noki Logistics on LinkedIn'=>'Noki Logistics auf LinkedIn folgen','Client stories'=>'Kundengeschichten','Our values'=>'Unsere Werte','Insights'=>'Einblicke','From our logistics blog'=>'Aus unserem Logistik-Blog','All Articles'=>'Alle Artikel','Read article'=>'Artikel lesen','Ready when you are'=>'Bereit, wenn Sie es sind','Chat on WhatsApp'=>'Auf WhatsApp chatten',
			'About Noki Logistics'=>'Über Noki Logistics','Home'=>'Startseite','About Us'=>'Über uns','Years of excellence'=>'Jahre Exzellenz','Our mission & values'=>'Unsere Mission & Werte','What drives us'=>'Was uns antreibt','Work With Us'=>'Mit uns arbeiten',"Let's move your business forward"=>'Bringen wir Ihr Geschäft voran','View Services'=>'Leistungen ansehen',
			"Let's talk about your shipment"=>'Sprechen wir über Ihre Sendung','Visit our office'=>'Besuchen Sie unser Büro','Call or WhatsApp'=>'Anrufen oder WhatsApp','Working hours'=>'Öffnungszeiten','Emergency line: 24/7'=>'Notfallnummer: 24/7','Get a free quote'=>'Kostenloses Angebot',
			'Behind every shipment'=>'Hinter jeder Sendung','Experienced people who care'=>'Erfahrene Menschen, die sich kümmern','Our culture'=>'Unsere Kultur','One team, one promise'=>'Ein Team, ein Versprechen','Join Our Team'=>'Unserem Team beitreten','Work with a team that delivers'=>'Arbeiten Sie mit einem Team, das liefert',
			'How pricing works'=>'So funktioniert die Preisgestaltung','No hidden fees, ever'=>'Keine versteckten Gebühren','Questions'=>'Fragen','Pricing FAQs'=>'Preis-FAQ','Get your custom quote'=>'Ihr individuelles Angebot','Request a Quote'=>'Angebot anfordern','WhatsApp Us'=>'WhatsApp',
			'Trusted across East Africa'=>'Vertrauen in ganz Ostafrika','Real results, real businesses'=>'Echte Ergebnisse, echte Unternehmen','Join hundreds of happy shippers'=>'Werden Sie Teil hunderter zufriedener Kunden','Why businesses choose Noki'=>'Warum Unternehmen Noki wählen','The Noki difference'=>'Der Noki-Unterschied','Logistics that works the way you do'=>'Logistik, die zu Ihrem Geschäft passt','On-time, every time'=>'Immer pünktlich','Dedicated coordinator'=>'Persönlicher Koordinator','Regional reach'=>'Regionale Reichweite','Fully insured cargo'=>'Voll versicherte Fracht','How it works'=>'So funktioniert es','Simple, from quote to delivery'=>'Einfach vom Angebot bis zur Lieferung','Start a Shipment'=>'Sendung starten','See the difference for yourself'=>'Erleben Sie den Unterschied',
			'Logistics Blog'=>'Logistik-Blog','No posts yet'=>'Noch keine Beiträge','Our Services'=>'Unsere Leistungen','End-to-end logistics'=>'End-to-End-Logistik','Freight solutions for every need'=>'Frachtlösungen für jeden Bedarf','Not sure which service you need?'=>'Unsicher, welchen Service Sie benötigen?','Speak to an Expert'=>'Mit einem Experten sprechen','Service'=>'Leistung','Key features'=>'Wichtige Merkmale','Need this service?'=>'Benötigen Sie diesen Service?','All services'=>'Alle Leistungen','Talk to us'=>'Sprechen Sie mit uns','WhatsApp Chat'=>'WhatsApp-Chat','Stay in the loop'=>'Bleiben Sie informiert','News & Events'=>'News & Events','Back to News & Events'=>'Zurück zu News & Events','Latest news'=>'Neueste Nachrichten','More news coming soon.'=>'Weitere Nachrichten folgen.','Need to ship something?'=>'Müssen Sie etwas versenden?','Recent articles'=>'Aktuelle Artikel','Need a quote?'=>'Benötigen Sie ein Angebot?',
			'Page Not Found'=>'Seite nicht gefunden',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Die gesuchte Seite existiert nicht oder wurde verschoben.','Back to Home'=>'Zur Startseite','Get in touch'=>'Kontakt aufnehmen','Subscribe for logistics tips & updates.'=>'Abonnieren Sie Logistik-Tipps und Updates.','Your email address'=>'Ihre E-Mail-Adresse','All rights reserved.'=>'Alle Rechte vorbehalten.','Privacy Policy'=>'Datenschutz','Terms of Service'=>'Nutzungsbedingungen'
		],
		'es' => [
			'Who We Are'=>'Quiénes somos','About Noki'=>'Sobre Noki','A logistics partner you can count on'=>'Un socio logístico en quien puede confiar','Our story'=>'Nuestra historia','Company'=>'Empresa','Why Choose Us'=>'Por qué elegirnos','What sets us apart'=>'Lo que nos diferencia','Our Team'=>'Nuestro equipo','The people behind Noki'=>'Las personas detrás de Noki','Join Us'=>'Únete a nosotros','Careers & openings'=>'Carreras y vacantes','Resources'=>'Recursos','Pricing'=>'Precios','Clear, fair rates'=>'Tarifas claras y justas','Testimonials'=>'Testimonios','What clients say'=>'Lo que dicen nuestros clientes','FAQ'=>'Preguntas frecuentes','Common questions'=>'Preguntas frecuentes','Services'=>'Servicios','Get a quote'=>'Solicitar cotización','Freight'=>'Carga','Logistics'=>'Logística','Reliable & insured'=>'Confiable y asegurado','Fast & secure'=>'Rápido y seguro','Contact'=>'Contacto','Call us anytime'=>'Llámenos cuando quiera','Get a Quote'=>'Solicitar cotización',
			'Trusted freight partner across East Africa'=>'Socio de carga confiable en África Oriental','Global reach, local expertise'=>'Alcance global, experiencia local','Cross-border specialists'=>'Especialistas transfronterizos','Our growing road fleet'=>'Nuestra creciente flota terrestre','Capacity to Move East Africa'=>'Capacidad para mover África Oriental','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics cuenta con la flota, el personal y la experiencia regional para mover carga comercial de forma confiable por Uganda y África Oriental.',
			'Get a Free Quote'=>'Obtener cotización gratis','Explore Services'=>'Explorar servicios','Our Services'=>'Nuestros servicios','Contact Us'=>'Contáctenos','Road Transport'=>'Transporte terrestre','Who we are'=>'Quiénes somos','What we offer'=>'Lo que ofrecemos','How we can help you move'=>'Cómo podemos ayudarle a mover su carga','All Services'=>'Todos los servicios','Learn more'=>'Más información','Why Noki'=>'Por qué Noki',"Built for businesses that can't afford delays"=>'Diseñado para empresas que no pueden permitirse retrasos','Delivering goods reliably'=>'Entregas confiables','Cutting-edge tracking'=>'Seguimiento avanzado','Personalised service'=>'Servicio personalizado',
			'Special highlights'=>'Destacados','Discover Noki Logistics!'=>'¡Descubra Noki Logistics!','View All News'=>'Ver todas las noticias','Read more'=>'Leer más','Transparent pricing'=>'Precios transparentes','Latest updates'=>'Últimas novedades','From Noki Logistics on LinkedIn'=>'Noki Logistics en LinkedIn','View on LinkedIn'=>'Ver en LinkedIn','Follow Noki Logistics on LinkedIn'=>'Seguir a Noki Logistics en LinkedIn','Client stories'=>'Historias de clientes','Our values'=>'Nuestros valores','Insights'=>'Ideas','From our logistics blog'=>'Desde nuestro blog de logística','All Articles'=>'Todos los artículos','Read article'=>'Leer artículo','Ready when you are'=>'Listos cuando usted lo esté','Chat on WhatsApp'=>'Chatear por WhatsApp',
			'About Noki Logistics'=>'Sobre Noki Logistics','Home'=>'Inicio','About Us'=>'Sobre nosotros','Years of excellence'=>'Años de excelencia','Our mission & values'=>'Nuestra misión y valores','What drives us'=>'Lo que nos impulsa','Work With Us'=>'Trabaje con nosotros',"Let's move your business forward"=>'Hagamos avanzar su negocio','View Services'=>'Ver servicios',
			"Let's talk about your shipment"=>'Hablemos de su envío','Visit our office'=>'Visite nuestra oficina','Call or WhatsApp'=>'Llame o escriba por WhatsApp','Working hours'=>'Horario','Emergency line: 24/7'=>'Línea de emergencia: 24/7','Get a free quote'=>'Obtener cotización gratis',
			'Behind every shipment'=>'Detrás de cada envío','Experienced people who care'=>'Personas con experiencia que se preocupan','Our culture'=>'Nuestra cultura','One team, one promise'=>'Un equipo, una promesa','Join Our Team'=>'Únase a nuestro equipo','Work with a team that delivers'=>'Trabaje con un equipo que cumple',
			'How pricing works'=>'Cómo funcionan los precios','No hidden fees, ever'=>'Sin cargos ocultos','Questions'=>'Preguntas','Pricing FAQs'=>'Preguntas sobre precios','Get your custom quote'=>'Obtenga su cotización personalizada','Request a Quote'=>'Solicitar cotización','WhatsApp Us'=>'WhatsApp',
			'Trusted across East Africa'=>'Confianza en toda África Oriental','Real results, real businesses'=>'Resultados reales, empresas reales','Join hundreds of happy shippers'=>'Únase a cientos de clientes satisfechos','Why businesses choose Noki'=>'Por qué las empresas eligen Noki','The Noki difference'=>'La diferencia Noki','Logistics that works the way you do'=>'Logística que funciona a su manera','On-time, every time'=>'Siempre a tiempo','Dedicated coordinator'=>'Coordinador dedicado','Regional reach'=>'Alcance regional','Fully insured cargo'=>'Carga totalmente asegurada','How it works'=>'Cómo funciona','Simple, from quote to delivery'=>'Simple, desde la cotización hasta la entrega','Start a Shipment'=>'Iniciar un envío','See the difference for yourself'=>'Compruebe la diferencia',
			'Logistics Blog'=>'Blog de logística','No posts yet'=>'Aún no hay artículos','Our Services'=>'Nuestros servicios','End-to-end logistics'=>'Logística de extremo a extremo','Freight solutions for every need'=>'Soluciones de carga para cada necesidad','Not sure which service you need?'=>'¿No sabe qué servicio necesita?','Speak to an Expert'=>'Hablar con un experto','Service'=>'Servicio','Key features'=>'Características principales','Need this service?'=>'¿Necesita este servicio?','All services'=>'Todos los servicios','Talk to us'=>'Hable con nosotros','WhatsApp Chat'=>'Chat de WhatsApp','Stay in the loop'=>'Manténgase informado','News & Events'=>'Noticias y eventos','Back to News & Events'=>'Volver a noticias y eventos','Latest news'=>'Últimas noticias','More news coming soon.'=>'Más noticias próximamente.','Need to ship something?'=>'¿Necesita enviar algo?','Recent articles'=>'Artículos recientes','Need a quote?'=>'¿Necesita una cotización?',
			'Page Not Found'=>'Página no encontrada',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Lo sentimos, la página que busca no existe o ha sido movida.','Back to Home'=>'Volver al inicio','Get in touch'=>'Contáctenos','Subscribe for logistics tips & updates.'=>'Suscríbase a consejos y novedades de logística.','Your email address'=>'Su correo electrónico','All rights reserved.'=>'Todos los derechos reservados.','Privacy Policy'=>'Política de privacidad','Terms of Service'=>'Términos del servicio'
		],
		'pl' => [
			'Who We Are'=>'O nas','About Noki'=>'O Noki','A logistics partner you can count on'=>'Partner logistyczny, na którym możesz polegać','Our story'=>'Nasza historia','Company'=>'Firma','Why Choose Us'=>'Dlaczego my','What sets us apart'=>'Co nas wyróżnia','Our Team'=>'Nasz zespół','The people behind Noki'=>'Ludzie tworzący Noki','Join Us'=>'Dołącz do nas','Careers & openings'=>'Kariera i oferty pracy','Resources'=>'Materiały','Pricing'=>'Cennik','Clear, fair rates'=>'Jasne i uczciwe stawki','Testimonials'=>'Opinie klientów','What clients say'=>'Co mówią klienci','FAQ'=>'FAQ','Common questions'=>'Częste pytania','Services'=>'Usługi','Get a quote'=>'Poproś o wycenę','Freight'=>'Transport','Logistics'=>'Logistyka','Reliable & insured'=>'Niezawodnie i z ubezpieczeniem','Fast & secure'=>'Szybko i bezpiecznie','Contact'=>'Kontakt','Call us anytime'=>'Zadzwoń do nas','Get a Quote'=>'Poproś o wycenę',
			'Trusted freight partner across East Africa'=>'Zaufany partner transportowy w Afryce Wschodniej','Global reach, local expertise'=>'Globalny zasięg, lokalne doświadczenie','Cross-border specialists'=>'Specjaliści od transportu transgranicznego','Our growing road fleet'=>'Nasza rosnąca flota drogowa','Capacity to Move East Africa'=>'Potencjał do obsługi Afryki Wschodniej','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics ma flotę, zespół i doświadczenie regionalne potrzebne do niezawodnego przewozu ładunków komercyjnych w Ugandzie i Afryce Wschodniej.',
			'Get a Free Quote'=>'Bezpłatna wycena','Explore Services'=>'Poznaj usługi','Our Services'=>'Nasze usługi','Contact Us'=>'Skontaktuj się','Road Transport'=>'Transport drogowy','Who we are'=>'O nas','What we offer'=>'Co oferujemy','How we can help you move'=>'Jak możemy pomóc w transporcie','All Services'=>'Wszystkie usługi','Learn more'=>'Dowiedz się więcej','Why Noki'=>'Dlaczego Noki',"Built for businesses that can't afford delays"=>'Dla firm, które nie mogą pozwolić sobie na opóźnienia','Delivering goods reliably'=>'Niezawodne dostawy','Cutting-edge tracking'=>'Nowoczesne śledzenie','Personalised service'=>'Spersonalizowana obsługa',
			'Special highlights'=>'Wyróżnione','Discover Noki Logistics!'=>'Poznaj Noki Logistics!','View All News'=>'Wszystkie aktualności','Read more'=>'Czytaj więcej','Transparent pricing'=>'Przejrzyste ceny','Latest updates'=>'Najnowsze informacje','From Noki Logistics on LinkedIn'=>'Noki Logistics na LinkedIn','View on LinkedIn'=>'Zobacz na LinkedIn','Follow Noki Logistics on LinkedIn'=>'Obserwuj Noki Logistics na LinkedIn','Client stories'=>'Historie klientów','Our values'=>'Nasze wartości','Insights'=>'Wiedza','From our logistics blog'=>'Z naszego bloga logistycznego','All Articles'=>'Wszystkie artykuły','Read article'=>'Czytaj artykuł','Ready when you are'=>'Gotowi, kiedy Ty jesteś','Chat on WhatsApp'=>'Napisz na WhatsApp',
			'About Noki Logistics'=>'O Noki Logistics','Home'=>'Strona główna','About Us'=>'O nas','Years of excellence'=>'Lata doskonałości','Our mission & values'=>'Nasza misja i wartości','What drives us'=>'Co nas napędza','Work With Us'=>'Współpracuj z nami',"Let's move your business forward"=>'Rozwijajmy Twój biznes','View Services'=>'Zobacz usługi',
			"Let's talk about your shipment"=>'Porozmawiajmy o Twojej przesyłce','Visit our office'=>'Odwiedź nasze biuro','Call or WhatsApp'=>'Zadzwoń lub WhatsApp','Working hours'=>'Godziny pracy','Emergency line: 24/7'=>'Linia alarmowa: 24/7','Get a free quote'=>'Bezpłatna wycena',
			'Behind every shipment'=>'Za każdą przesyłką','Experienced people who care'=>'Doświadczeni ludzie, którym zależy','Our culture'=>'Nasza kultura','One team, one promise'=>'Jeden zespół, jedna obietnica','Join Our Team'=>'Dołącz do zespołu','Work with a team that delivers'=>'Pracuj z zespołem, który dowozi wyniki',
			'How pricing works'=>'Jak działa wycena','No hidden fees, ever'=>'Bez ukrytych opłat','Questions'=>'Pytania','Pricing FAQs'=>'FAQ dotyczące cen','Get your custom quote'=>'Uzyskaj indywidualną wycenę','Request a Quote'=>'Poproś o wycenę','WhatsApp Us'=>'WhatsApp',
			'Trusted across East Africa'=>'Zaufanie w całej Afryce Wschodniej','Real results, real businesses'=>'Prawdziwe wyniki, prawdziwe firmy','Join hundreds of happy shippers'=>'Dołącz do setek zadowolonych klientów','Why businesses choose Noki'=>'Dlaczego firmy wybierają Noki','The Noki difference'=>'Różnica Noki','Logistics that works the way you do'=>'Logistyka dopasowana do Twojego biznesu','On-time, every time'=>'Zawsze na czas','Dedicated coordinator'=>'Dedykowany koordynator','Regional reach'=>'Zasięg regionalny','Fully insured cargo'=>'Pełne ubezpieczenie ładunku','How it works'=>'Jak to działa','Simple, from quote to delivery'=>'Prosto od wyceny do dostawy','Start a Shipment'=>'Rozpocznij wysyłkę','See the difference for yourself'=>'Zobacz różnicę',
			'Logistics Blog'=>'Blog logistyczny','No posts yet'=>'Brak artykułów','Our Services'=>'Nasze usługi','End-to-end logistics'=>'Logistyka end-to-end','Freight solutions for every need'=>'Rozwiązania transportowe na każdą potrzebę','Not sure which service you need?'=>'Nie wiesz, której usługi potrzebujesz?','Speak to an Expert'=>'Porozmawiaj z ekspertem','Service'=>'Usługa','Key features'=>'Najważniejsze cechy','Need this service?'=>'Potrzebujesz tej usługi?','All services'=>'Wszystkie usługi','Talk to us'=>'Porozmawiaj z nami','WhatsApp Chat'=>'Czat WhatsApp','Stay in the loop'=>'Bądź na bieżąco','News & Events'=>'Aktualności i wydarzenia','Back to News & Events'=>'Wróć do aktualności','Latest news'=>'Najnowsze wiadomości','More news coming soon.'=>'Więcej wiadomości wkrótce.','Need to ship something?'=>'Potrzebujesz coś wysłać?','Recent articles'=>'Najnowsze artykuły','Need a quote?'=>'Potrzebujesz wyceny?',
			'Page Not Found'=>'Nie znaleziono strony',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Przepraszamy, szukana strona nie istnieje lub została przeniesiona.','Back to Home'=>'Wróć na stronę główną','Get in touch'=>'Skontaktuj się','Subscribe for logistics tips & updates.'=>'Zapisz się po porady logistyczne i aktualności.','Your email address'=>'Twój adres e-mail','All rights reserved.'=>'Wszelkie prawa zastrzeżone.','Privacy Policy'=>'Polityka prywatności','Terms of Service'=>'Warunki korzystania'
		],
	];
	$extras = [
		'zh' => [
			'Moving your cargo '=>'让您的货物运得','further, faster'=>'更远、更快',' &amp; safer'=>'且更安全','&amp; safer'=>'且更安全',' & safer'=>'且更安全','& safer'=>'且更安全',
			'Air, sea &amp; road freight, '=>'空运、海运和公路运输，','Air, sea & road freight, '=>'空运、海运和公路运输，','handled end to end'=>'端到端全程处理',
			'Reliable delivery across '=>'可靠配送覆盖','East Africa'=>'东非','Capacity to '=>'具备能力','Move East Africa'=>'运输整个东非',
			'Shipments Delivered'=>'已交付货运','Years of Experience'=>'行业经验年数','On-Time Delivery'=>'准时交付率','Customer Support'=>'客户支持',
			'Featured highlights'=>'精选亮点','Previous slide'=>'上一张','Next slide'=>'下一张','More About Us'=>'更多关于我们','Learn More'=>'了解更多',
			'Connecting Uganda to the world'=>'连接乌干达与世界','Local expertise'=>'本地专业经验','The Noki Logistics team'=>'Noki Logistics 团队',
			'Help centre'=>'帮助中心','Frequently asked questions'=>'常见问题','Got questions?'=>'有问题吗？','Everything you need to know'=>'您需要了解的一切',
			"Can't find your answer below? Call or WhatsApp us — we're happy to help."=>'没有找到答案？请致电或通过 WhatsApp 联系我们，我们很乐意帮助您。',
			'Still have questions?'=>'还有问题吗？','Our team is ready to help with anything about your shipment.'=>'我们的团队随时为您的货运需求提供帮助。','Call Us'=>'致电我们',
			'Tell us about your shipment and our team will send an itemised quote within 2 hours during business hours.'=>'告诉我们您的货运需求，我们的团队将在工作时间内 2 小时内发送明细报价。',
			'Full name *'=>'姓名 *','Email address *'=>'电子邮箱 *','Phone number *'=>'电话号码 *','Service needed'=>'所需服务','Select a service…'=>'选择服务…','Customs Clearance'=>'清关','Warehousing'=>'仓储','General Enquiry'=>'一般咨询',
			'Origin (from)'=>'起运地','Destination (to)'=>'目的地','Cargo details'=>'货物详情','Message *'=>'留言 *','Get My Free Quote'=>'获取免费报价','Fastest way to reach us'=>'最快联系我们的方式',
			'Prefer to chat? Message us on WhatsApp for the quickest response — usually within minutes.'=>'更喜欢聊天？请通过 WhatsApp 联系我们，通常几分钟内即可回复。',
			'Your full name'=>'您的姓名','Weight / volume / type of goods'=>'重量 / 体积 / 货物类型','Describe your shipment or enquiry…'=>'描述您的货运或咨询内容…','Noki Logistics location map'=>'Noki Logistics 位置地图',
			'Essentials'=>'基础方案','Domestic Delivery'=>'国内配送','From quote'=>'按报价','Most popular'=>'最受欢迎','Import / Export'=>'进出口','Custom'=>'定制','Business'=>'企业方案','Contract Logistics'=>'合同物流','Tailored'=>'定制方案','Talk to Sales'=>'联系销售',
			'Same-day & next-day options'=>'当日及次日配送','Kampala & nationwide coverage'=>'覆盖坎帕拉及全国','Live tracking updates'=>'实时追踪更新','Proof of delivery'=>'交付证明','Licensed customs clearing'=>'持证清关','Cargo insurance options'=>'货物保险选项','Volume & retainer rates'=>'批量及长期合作价格','Warehousing & inventory'=>'仓储与库存','Regional cross-border trucking'=>'区域跨境公路运输','Account management & reporting'=>'客户管理与报告',
			'Prices are quoted in UGX or USD depending on the route. Ask about volume discounts for regular shippers.'=>'价格根据线路以 UGX 或 USD 报价。长期发货客户可咨询批量优惠。',
			'How quickly will I get a quote?'=>'多久可以收到报价？','What affects the price of freight?'=>'哪些因素会影响运费？','Do you offer discounts for regular shipments?'=>'长期发货有折扣吗？','Are customs duties included?'=>'是否包含关税？',
			'Tell us what you\'re shipping and we\'ll send a clear, itemised price.'=>'告诉我们您要运输的货物，我们会发送清晰的明细报价。',
			'Importers'=>'进口商','Manufacturers'=>'制造商','Retailers'=>'零售商','NGOs & Aid'=>'非政府组织与援助机构','E-commerce'=>'电商','Wholesalers'=>'批发商','What our clients say'=>'客户评价',
			'Reliability'=>'可靠性','Innovation'=>'创新','Sustainability'=>'可持续发展','Customer-first'=>'客户至上','Follow on LinkedIn'=>'在 LinkedIn 关注','View LinkedIn'=>'查看 LinkedIn','Logistics'=>'物流'
		],
		'fr' => [
			'Moving your cargo '=>'Transportez vos marchandises ','further, faster'=>'plus loin, plus vite',' &amp; safer'=>' et en toute sécurité','&amp; safer'=>'et en toute sécurité','Air, sea &amp; road freight, '=>'Fret aérien, maritime et routier, ','Air, sea & road freight, '=>'Fret aérien, maritime et routier, ','handled end to end'=>'géré de bout en bout','Reliable delivery across '=>'Livraison fiable dans toute ','East Africa'=>"l’Afrique de l’Est",'Capacity to '=>'La capacité de ','Move East Africa'=>"faire avancer l’Afrique de l’Est",'Shipments Delivered'=>'Expéditions livrées','Years of Experience'=>"Années d'expérience",'On-Time Delivery'=>'Livraisons à l’heure','Customer Support'=>'Assistance client',
			'Featured highlights'=>'À la une','Previous slide'=>'Diapositive précédente','Next slide'=>'Diapositive suivante','More About Us'=>'En savoir plus sur nous','Learn More'=>'En savoir plus',
			'Connecting Uganda to the world'=>"Relier l’Ouganda au monde",'Local expertise'=>'Expertise locale','The Noki Logistics team'=>"L’équipe Noki Logistics",
			'Help centre'=>"Centre d’aide",'Frequently asked questions'=>'Questions fréquentes','Got questions?'=>'Des questions ?','Everything you need to know'=>'Tout ce que vous devez savoir',
			"Can't find your answer below? Call or WhatsApp us — we're happy to help."=>"Vous ne trouvez pas votre réponse ? Appelez-nous ou contactez-nous sur WhatsApp.",
			'Still have questions?'=>'Encore des questions ?','Our team is ready to help with anything about your shipment.'=>'Notre équipe est prête à vous aider pour votre expédition.','Call Us'=>'Appelez-nous',
			'Tell us about your shipment and our team will send an itemised quote within 2 hours during business hours.'=>"Parlez-nous de votre envoi et notre équipe vous enverra un devis détaillé sous 2 heures pendant les heures ouvrables.",
			'Full name *'=>'Nom complet *','Email address *'=>'Adresse e-mail *','Phone number *'=>'Numéro de téléphone *','Service needed'=>'Service souhaité','Select a service…'=>'Sélectionnez un service…','Customs Clearance'=>'Dédouanement','Warehousing'=>'Entreposage','General Enquiry'=>'Demande générale',
			'Origin (from)'=>'Origine','Destination (to)'=>'Destination','Cargo details'=>'Détails de la marchandise','Message *'=>'Message *','Get My Free Quote'=>'Obtenir mon devis gratuit','Fastest way to reach us'=>'Le moyen le plus rapide de nous joindre',
			'Prefer to chat? Message us on WhatsApp for the quickest response — usually within minutes.'=>"Vous préférez discuter ? Écrivez-nous sur WhatsApp pour une réponse rapide, généralement en quelques minutes.",
			'Your full name'=>'Votre nom complet','Weight / volume / type of goods'=>'Poids / volume / type de marchandises','Describe your shipment or enquiry…'=>'Décrivez votre envoi ou votre demande…','Noki Logistics location map'=>'Carte de localisation de Noki Logistics',
			'Essentials'=>'Essentiel','Domestic Delivery'=>'Livraison nationale','From quote'=>'Sur devis','Most popular'=>'Le plus populaire','Import / Export'=>'Import / Export','Custom'=>'Sur mesure','Business'=>'Entreprise','Contract Logistics'=>'Logistique contractuelle','Tailored'=>'Personnalisé','Talk to Sales'=>'Parler aux ventes',
			'Same-day & next-day options'=>'Livraison le jour même ou le lendemain','Kampala & nationwide coverage'=>'Kampala et couverture nationale','Live tracking updates'=>'Suivi en temps réel','Proof of delivery'=>'Preuve de livraison','Licensed customs clearing'=>'Dédouanement agréé','Cargo insurance options'=>"Options d’assurance cargo",'Volume & retainer rates'=>'Tarifs volume et contrat','Warehousing & inventory'=>'Entreposage et stocks','Regional cross-border trucking'=>'Transport routier transfrontalier régional','Account management & reporting'=>'Gestion de compte et rapports',
			'Prices are quoted in UGX or USD depending on the route. Ask about volume discounts for regular shippers.'=>'Les prix sont indiqués en UGX ou USD selon l’itinéraire. Demandez nos remises de volume pour les expéditeurs réguliers.',
			'How quickly will I get a quote?'=>'Sous quel délai recevrai-je un devis ?','What affects the price of freight?'=>'Qu’est-ce qui influence le prix du fret ?','Do you offer discounts for regular shipments?'=>'Proposez-vous des remises pour les expéditions régulières ?','Are customs duties included?'=>'Les droits de douane sont-ils inclus ?',
			"Tell us what you're shipping and we'll send a clear, itemised price."=>'Dites-nous ce que vous expédiez et nous vous enverrons un prix clair et détaillé.',
			'Importers'=>'Importateurs','Manufacturers'=>'Fabricants','Retailers'=>'Détaillants','NGOs & Aid'=>'ONG & aide','E-commerce'=>'E-commerce','Wholesalers'=>'Grossistes','What our clients say'=>'Ce que disent nos clients',
			'Reliability'=>'Fiabilité','Innovation'=>'Innovation','Sustainability'=>'Durabilité','Customer-first'=>'Priorité au client','Follow on LinkedIn'=>'Suivre sur LinkedIn','View LinkedIn'=>'Voir LinkedIn','Logistics'=>'Logistique'
		],
		'de' => [
			'Moving your cargo '=>'Wir bewegen Ihre Fracht ','further, faster'=>'weiter und schneller',' &amp; safer'=>' und sicherer','&amp; safer'=>'und sicherer','Air, sea &amp; road freight, '=>'Luft-, See- und Straßentransport, ','Air, sea & road freight, '=>'Luft-, See- und Straßentransport, ','handled end to end'=>'durchgängig abgewickelt','Reliable delivery across '=>'Zuverlässige Lieferung in ganz ','East Africa'=>'Ostafrika','Capacity to '=>'Kapazität, ','Move East Africa'=>'Ostafrika zu bewegen','Shipments Delivered'=>'Sendungen zugestellt','Years of Experience'=>'Jahre Erfahrung','On-Time Delivery'=>'Pünktliche Lieferung','Customer Support'=>'Kundensupport',
			'Featured highlights'=>'Highlights','Previous slide'=>'Vorherige Folie','Next slide'=>'Nächste Folie','More About Us'=>'Mehr über uns','Learn More'=>'Mehr erfahren',
			'Connecting Uganda to the world'=>'Uganda mit der Welt verbinden','Local expertise'=>'Lokale Expertise','The Noki Logistics team'=>'Das Noki-Logistics-Team',
			'Help centre'=>'Hilfezentrum','Frequently asked questions'=>'Häufig gestellte Fragen','Got questions?'=>'Fragen?','Everything you need to know'=>'Alles, was Sie wissen müssen',
			"Can't find your answer below? Call or WhatsApp us — we're happy to help."=>'Keine passende Antwort gefunden? Rufen Sie uns an oder schreiben Sie uns auf WhatsApp.',
			'Still have questions?'=>'Noch Fragen?','Our team is ready to help with anything about your shipment.'=>'Unser Team hilft Ihnen gerne bei allen Fragen zu Ihrer Sendung.','Call Us'=>'Anrufen',
			'Tell us about your shipment and our team will send an itemised quote within 2 hours during business hours.'=>'Beschreiben Sie Ihre Sendung und unser Team sendet Ihnen während der Geschäftszeiten innerhalb von 2 Stunden ein detailliertes Angebot.',
			'Full name *'=>'Vollständiger Name *','Email address *'=>'E-Mail-Adresse *','Phone number *'=>'Telefonnummer *','Service needed'=>'Benötigter Service','Select a service…'=>'Service auswählen…','Customs Clearance'=>'Zollabfertigung','Warehousing'=>'Lagerhaltung','General Enquiry'=>'Allgemeine Anfrage',
			'Origin (from)'=>'Ursprung','Destination (to)'=>'Ziel','Cargo details'=>'Frachtdetails','Message *'=>'Nachricht *','Get My Free Quote'=>'Kostenloses Angebot erhalten','Fastest way to reach us'=>'Schnellster Kontakt',
			'Prefer to chat? Message us on WhatsApp for the quickest response — usually within minutes.'=>'Sie möchten lieber chatten? Schreiben Sie uns auf WhatsApp – meist antworten wir innerhalb weniger Minuten.',
			'Your full name'=>'Ihr vollständiger Name','Weight / volume / type of goods'=>'Gewicht / Volumen / Warenart','Describe your shipment or enquiry…'=>'Beschreiben Sie Ihre Sendung oder Anfrage…','Noki Logistics location map'=>'Standortkarte von Noki Logistics',
			'Essentials'=>'Basis','Domestic Delivery'=>'Inlandszustellung','From quote'=>'Nach Angebot','Most popular'=>'Am beliebtesten','Import / Export'=>'Import / Export','Custom'=>'Individuell','Business'=>'Business','Contract Logistics'=>'Kontraktlogistik','Tailored'=>'Maßgeschneidert','Talk to Sales'=>'Vertrieb kontaktieren',
			'Same-day & next-day options'=>'Same-Day- und Next-Day-Optionen','Kampala & nationwide coverage'=>'Kampala und landesweite Abdeckung','Live tracking updates'=>'Live-Tracking','Proof of delivery'=>'Zustellnachweis','Licensed customs clearing'=>'Lizenzierte Zollabfertigung','Cargo insurance options'=>'Transportversicherungsoptionen','Volume & retainer rates'=>'Volumen- und Vertragskonditionen','Warehousing & inventory'=>'Lager und Bestand','Regional cross-border trucking'=>'Regionale grenzüberschreitende Lkw-Transporte','Account management & reporting'=>'Account-Management und Reporting',
			'Prices are quoted in UGX or USD depending on the route. Ask about volume discounts for regular shippers.'=>'Preise werden je nach Strecke in UGX oder USD angegeben. Fragen Sie nach Mengenrabatten für regelmäßige Sendungen.',
			'How quickly will I get a quote?'=>'Wie schnell erhalte ich ein Angebot?','What affects the price of freight?'=>'Was beeinflusst den Frachtpreis?','Do you offer discounts for regular shipments?'=>'Gibt es Rabatte für regelmäßige Sendungen?','Are customs duties included?'=>'Sind Zölle enthalten?',
			"Tell us what you're shipping and we'll send a clear, itemised price."=>'Sagen Sie uns, was Sie versenden, und wir senden Ihnen einen klaren, detaillierten Preis.',
			'Importers'=>'Importeure','Manufacturers'=>'Hersteller','Retailers'=>'Einzelhändler','NGOs & Aid'=>'NGOs & Hilfsorganisationen','E-commerce'=>'E-Commerce','Wholesalers'=>'Großhändler','What our clients say'=>'Was unsere Kunden sagen',
			'Reliability'=>'Zuverlässigkeit','Innovation'=>'Innovation','Sustainability'=>'Nachhaltigkeit','Customer-first'=>'Kundenorientierung','Follow on LinkedIn'=>'Auf LinkedIn folgen','View LinkedIn'=>'LinkedIn ansehen','Logistics'=>'Logistik'
		],
		'es' => [
			'Moving your cargo '=>'Movemos su carga ','further, faster'=>'más lejos y más rápido',' &amp; safer'=>' y con mayor seguridad','&amp; safer'=>'y con mayor seguridad','Air, sea &amp; road freight, '=>'Carga aérea, marítima y terrestre, ','Air, sea & road freight, '=>'Carga aérea, marítima y terrestre, ','handled end to end'=>'gestionada de principio a fin','Reliable delivery across '=>'Entrega confiable en toda ','East Africa'=>'África Oriental','Capacity to '=>'Capacidad para ','Move East Africa'=>'mover África Oriental','Shipments Delivered'=>'Envíos entregados','Years of Experience'=>'Años de experiencia','On-Time Delivery'=>'Entrega puntual','Customer Support'=>'Atención al cliente',
			'Featured highlights'=>'Destacados','Previous slide'=>'Diapositiva anterior','Next slide'=>'Siguiente diapositiva','More About Us'=>'Más sobre nosotros','Learn More'=>'Más información',
			'Connecting Uganda to the world'=>'Conectando Uganda con el mundo','Local expertise'=>'Experiencia local','The Noki Logistics team'=>'El equipo de Noki Logistics',
			'Help centre'=>'Centro de ayuda','Frequently asked questions'=>'Preguntas frecuentes','Got questions?'=>'¿Tiene preguntas?','Everything you need to know'=>'Todo lo que necesita saber',
			"Can't find your answer below? Call or WhatsApp us — we're happy to help."=>'¿No encuentra su respuesta? Llámenos o escríbanos por WhatsApp.',
			'Still have questions?'=>'¿Aún tiene preguntas?','Our team is ready to help with anything about your shipment.'=>'Nuestro equipo está listo para ayudarle con cualquier aspecto de su envío.','Call Us'=>'Llámenos',
			'Tell us about your shipment and our team will send an itemised quote within 2 hours during business hours.'=>'Cuéntenos sobre su envío y nuestro equipo le enviará una cotización detallada en un plazo de 2 horas durante el horario laboral.',
			'Full name *'=>'Nombre completo *','Email address *'=>'Correo electrónico *','Phone number *'=>'Número de teléfono *','Service needed'=>'Servicio requerido','Select a service…'=>'Seleccione un servicio…','Customs Clearance'=>'Despacho de aduanas','Warehousing'=>'Almacenamiento','General Enquiry'=>'Consulta general',
			'Origin (from)'=>'Origen','Destination (to)'=>'Destino','Cargo details'=>'Detalles de la carga','Message *'=>'Mensaje *','Get My Free Quote'=>'Obtener mi cotización gratis','Fastest way to reach us'=>'La forma más rápida de contactarnos',
			'Prefer to chat? Message us on WhatsApp for the quickest response — usually within minutes.'=>'¿Prefiere chatear? Escríbanos por WhatsApp para obtener la respuesta más rápida, normalmente en pocos minutos.',
			'Your full name'=>'Su nombre completo','Weight / volume / type of goods'=>'Peso / volumen / tipo de mercancía','Describe your shipment or enquiry…'=>'Describa su envío o consulta…','Noki Logistics location map'=>'Mapa de ubicación de Noki Logistics',
			'Essentials'=>'Esencial','Domestic Delivery'=>'Entrega nacional','From quote'=>'Según cotización','Most popular'=>'Más popular','Import / Export'=>'Importación / Exportación','Custom'=>'Personalizado','Business'=>'Empresas','Contract Logistics'=>'Logística contractual','Tailored'=>'A medida','Talk to Sales'=>'Hablar con ventas',
			'Same-day & next-day options'=>'Opciones para el mismo día y día siguiente','Kampala & nationwide coverage'=>'Cobertura en Kampala y todo el país','Live tracking updates'=>'Seguimiento en tiempo real','Proof of delivery'=>'Comprobante de entrega','Licensed customs clearing'=>'Despacho aduanero autorizado','Cargo insurance options'=>'Opciones de seguro de carga','Volume & retainer rates'=>'Tarifas por volumen y contrato','Warehousing & inventory'=>'Almacén e inventario','Regional cross-border trucking'=>'Transporte terrestre transfronterizo regional','Account management & reporting'=>'Gestión de cuenta e informes',
			'Prices are quoted in UGX or USD depending on the route. Ask about volume discounts for regular shippers.'=>'Los precios se cotizan en UGX o USD según la ruta. Pregunte por descuentos por volumen para envíos frecuentes.',
			'How quickly will I get a quote?'=>'¿En cuánto tiempo recibiré una cotización?','What affects the price of freight?'=>'¿Qué afecta al precio del transporte?','Do you offer discounts for regular shipments?'=>'¿Ofrecen descuentos para envíos frecuentes?','Are customs duties included?'=>'¿Están incluidos los aranceles?',
			"Tell us what you're shipping and we'll send a clear, itemised price."=>'Díganos qué va a enviar y le enviaremos un precio claro y detallado.',
			'Importers'=>'Importadores','Manufacturers'=>'Fabricantes','Retailers'=>'Minoristas','NGOs & Aid'=>'ONG y ayuda','E-commerce'=>'Comercio electrónico','Wholesalers'=>'Mayoristas','What our clients say'=>'Lo que dicen nuestros clientes',
			'Reliability'=>'Fiabilidad','Innovation'=>'Innovación','Sustainability'=>'Sostenibilidad','Customer-first'=>'El cliente primero','Follow on LinkedIn'=>'Seguir en LinkedIn','View LinkedIn'=>'Ver LinkedIn','Logistics'=>'Logística'
		],
		'pl' => [
			'Moving your cargo '=>'Przewozimy Twój ładunek ','further, faster'=>'dalej i szybciej',' &amp; safer'=>' oraz bezpieczniej','&amp; safer'=>'oraz bezpieczniej','Air, sea &amp; road freight, '=>'Fracht lotniczy, morski i drogowy, ','Air, sea & road freight, '=>'Fracht lotniczy, morski i drogowy, ','handled end to end'=>'obsługiwany od początku do końca','Reliable delivery across '=>'Niezawodne dostawy w całej ','East Africa'=>'Afryce Wschodniej','Capacity to '=>'Potencjał, by ','Move East Africa'=>'obsługiwać Afrykę Wschodnią','Shipments Delivered'=>'Dostarczone przesyłki','Years of Experience'=>'Lata doświadczenia','On-Time Delivery'=>'Terminowe dostawy','Customer Support'=>'Obsługa klienta',
			'Featured highlights'=>'Najważniejsze informacje','Previous slide'=>'Poprzedni slajd','Next slide'=>'Następny slajd','More About Us'=>'Więcej o nas','Learn More'=>'Dowiedz się więcej',
			'Connecting Uganda to the world'=>'Łączymy Ugandę ze światem','Local expertise'=>'Lokalne doświadczenie','The Noki Logistics team'=>'Zespół Noki Logistics',
			'Help centre'=>'Centrum pomocy','Frequently asked questions'=>'Najczęściej zadawane pytania','Got questions?'=>'Masz pytania?','Everything you need to know'=>'Wszystko, co musisz wiedzieć',
			"Can't find your answer below? Call or WhatsApp us — we're happy to help."=>'Nie znalazłeś odpowiedzi? Zadzwoń lub napisz do nas na WhatsApp.',
			'Still have questions?'=>'Masz jeszcze pytania?','Our team is ready to help with anything about your shipment.'=>'Nasz zespół pomoże w każdej sprawie dotyczącej Twojej przesyłki.','Call Us'=>'Zadzwoń',
			'Tell us about your shipment and our team will send an itemised quote within 2 hours during business hours.'=>'Opowiedz nam o przesyłce, a nasz zespół wyśle szczegółową wycenę w ciągu 2 godzin w godzinach pracy.',
			'Full name *'=>'Imię i nazwisko *','Email address *'=>'Adres e-mail *','Phone number *'=>'Numer telefonu *','Service needed'=>'Potrzebna usługa','Select a service…'=>'Wybierz usługę…','Customs Clearance'=>'Odprawa celna','Warehousing'=>'Magazynowanie','General Enquiry'=>'Zapytanie ogólne',
			'Origin (from)'=>'Miejsce nadania','Destination (to)'=>'Miejsce docelowe','Cargo details'=>'Szczegóły ładunku','Message *'=>'Wiadomość *','Get My Free Quote'=>'Uzyskaj bezpłatną wycenę','Fastest way to reach us'=>'Najszybszy kontakt',
			'Prefer to chat? Message us on WhatsApp for the quickest response — usually within minutes.'=>'Wolisz czat? Napisz do nas na WhatsApp — zwykle odpowiadamy w ciągu kilku minut.',
			'Your full name'=>'Imię i nazwisko','Weight / volume / type of goods'=>'Waga / objętość / rodzaj towaru','Describe your shipment or enquiry…'=>'Opisz przesyłkę lub zapytanie…','Noki Logistics location map'=>'Mapa lokalizacji Noki Logistics',
			'Essentials'=>'Podstawowy','Domestic Delivery'=>'Dostawa krajowa','From quote'=>'Według wyceny','Most popular'=>'Najpopularniejszy','Import / Export'=>'Import / Eksport','Custom'=>'Indywidualnie','Business'=>'Biznes','Contract Logistics'=>'Logistyka kontraktowa','Tailored'=>'Dopasowane','Talk to Sales'=>'Porozmawiaj ze sprzedażą',
			'Same-day & next-day options'=>'Opcje na ten sam i następny dzień','Kampala & nationwide coverage'=>'Kampala i zasięg ogólnokrajowy','Live tracking updates'=>'Śledzenie na żywo','Proof of delivery'=>'Potwierdzenie dostawy','Licensed customs clearing'=>'Licencjonowana odprawa celna','Cargo insurance options'=>'Opcje ubezpieczenia ładunku','Volume & retainer rates'=>'Stawki wolumenowe i abonamentowe','Warehousing & inventory'=>'Magazynowanie i zapasy','Regional cross-border trucking'=>'Regionalny transport transgraniczny','Account management & reporting'=>'Obsługa konta i raportowanie',
			'Prices are quoted in UGX or USD depending on the route. Ask about volume discounts for regular shippers.'=>'Ceny podajemy w UGX lub USD zależnie od trasy. Zapytaj o rabaty wolumenowe dla regularnych wysyłek.',
			'How quickly will I get a quote?'=>'Jak szybko otrzymam wycenę?','What affects the price of freight?'=>'Co wpływa na cenę transportu?','Do you offer discounts for regular shipments?'=>'Czy oferujecie rabaty dla regularnych wysyłek?','Are customs duties included?'=>'Czy cło jest wliczone?',
			"Tell us what you're shipping and we'll send a clear, itemised price."=>'Powiedz nam, co wysyłasz, a prześlemy jasną, szczegółową wycenę.',
			'Importers'=>'Importerzy','Manufacturers'=>'Producenci','Retailers'=>'Detaliści','NGOs & Aid'=>'NGO i pomoc','E-commerce'=>'E-commerce','Wholesalers'=>'Hurtownicy','What our clients say'=>'Co mówią nasi klienci',
			'Reliability'=>'Niezawodność','Innovation'=>'Innowacja','Sustainability'=>'Zrównoważony rozwój','Customer-first'=>'Klient na pierwszym miejscu','Follow on LinkedIn'=>'Obserwuj na LinkedIn','View LinkedIn'=>'Zobacz LinkedIn','Logistics'=>'Logistyka'
		],
	];

	$auto = get_option( 'noki_ui_auto_translations', [] );
	if ( is_array( $auto ) ) {
		foreach ( $auto as $lang => $map ) {
			if ( is_array( $map ) ) {
				$manual[ $lang ] = array_merge( $map, $manual[ $lang ] ?? [] );
			}
		}
	}
	foreach ( $extras as $lang => $map ) {
		$manual[ $lang ] = array_merge( $map, $manual[ $lang ] ?? [] );
	}
	return $manual;
}

function noki_translate_fixed_html( $html ) {
	if ( is_admin() || ! function_exists( 'pll_current_language' ) ) return $html;
	$lang = pll_current_language( 'slug' );
	if ( ! $lang || 'en' === $lang ) return $html;

	$all = noki_ui_translations();
	if ( empty( $all[ $lang ] ) || ! is_string( $html ) || '' === $html ) return $html;

	/*
	 * IMPORTANT: translate visible text only.
	 * Running strtr() over the complete HTML can alter stylesheet/script URLs,
	 * class names and attributes (for example words such as "about" or
	 * "contact"), which makes translated pages render as unstyled/plain text.
	 * Script/style blocks and all HTML tags are preserved byte-for-byte.
	 */
	$parts = preg_split(
		'~(<script\\b[^>]*>.*?</script>|<style\\b[^>]*>.*?</style>|<noscript\\b[^>]*>.*?</noscript>|<[^>]+>)~is',
		$html,
		-1,
		PREG_SPLIT_DELIM_CAPTURE
	);

	if ( false === $parts ) return $html;

	foreach ( $parts as $i => $part ) {
		if ( '' === $part ) continue;

		if ( '<' === $part[0] ) {
			// Translate only human-facing attributes; never touch href/src/class/style/data-*.
			if ( ! preg_match( '~^<(?:script|style|noscript)\\b~i', $part ) ) {
				$parts[ $i ] = preg_replace_callback(
					'~\\b(placeholder|aria-label|title|alt)\\s*=\\s*(["\\\'])(.*?)\\2~is',
					function ( $m ) use ( $all, $lang ) {
						$value = strtr( $m[3], $all[ $lang ] );
						return $m[1] . '=' . $m[2] . $value . $m[2];
					},
					$part
				);
			}
			continue;
		}

		$parts[ $i ] = strtr( $part, $all[ $lang ] );
	}

	return implode( '', $parts );
}

function noki_start_translation_buffer() {
	if ( is_admin() || wp_doing_ajax() || wp_doing_cron() ) return;
	if ( function_exists( 'pll_current_language' ) && 'en' !== pll_current_language( 'slug' ) ) {
		ob_start( 'noki_translate_fixed_html' );
	}
}
add_action( 'template_redirect', 'noki_start_translation_buffer', 0 );
