<?php
defined( 'ABSPATH' ) || exit;

/**
 * Noki UI translation layer.
 * Translates fixed theme copy that lives in PHP templates while keeping
 * editorial content in Polylang translation posts.
 */
function noki_ui_translations() {
	$manual = [
		'zh' => [
			'Who We Are'=>'关于我们','About Noki'=>'关于 Noki','A logistics partner you can count on'=>'值得信赖的物流合作伙伴',
			'10+ years moving cargo across East Africa with reliability, transparency and care.'=>'十余年来，我们以可靠、透明和用心的服务运输东非货物。',
			'Our story'=>'我们的故事','Company'=>'公司','Why Choose Us'=>'为何选择我们','What sets us apart'=>'我们的优势','Our Team'=>'我们的团队','The people behind Noki'=>'Noki 背后的团队',
			'Join Us'=>'加入我们','Careers & openings'=>'职业机会与职位','Resources'=>'资源','Pricing'=>'价格','Clear, fair rates'=>'清晰、公平的价格','Testimonials'=>'客户评价','What clients say'=>'客户怎么说','FAQ'=>'常见问题','Common questions'=>'常见问题',
			'Services'=>'服务','End-to-end supply chain, handled with precision'=>'精准管理端到端供应链','Air, sea and road freight plus customs and warehousing — one trusted partner across East Africa.'=>'空运、海运、公路运输、清关和仓储——一个值得信赖的东非物流伙伴。',
			'Get a quote'=>'获取报价','Freight'=>'货运','Logistics'=>'物流','Reliable & insured'=>'可靠并有保险','Fast & secure'=>'快速且安全','Contact'=>'联系我们','Call us anytime'=>'随时致电我们','Get a Quote'=>'获取报价',
			'Moving your cargo further, faster & safer'=>'让您的货物运得更远、更快、更安全','Trusted freight partner across East Africa'=>'东非值得信赖的货运伙伴','From Kampala to the world — air, sea and road freight, customs clearance and warehousing you can rely on.'=>'从坎帕拉到全球——可靠的空运、海运、公路运输、清关和仓储服务。',
			'Global reach, local expertise'=>'全球网络，本地专业','One trusted partner for your entire supply chain — across East Africa and beyond.'=>'一个值得信赖的合作伙伴，覆盖东非及全球的整个供应链。',
			'Cross-border specialists'=>'跨境运输专家','Reliable delivery across East Africa'=>'东非可靠配送','Kenya, Tanzania, Rwanda, DRC and South Sudan — on time, every time.'=>'肯尼亚、坦桑尼亚、卢旺达、刚果（金）和南苏丹——始终准时。',
			'Our growing road fleet'=>'不断扩大的公路运输车队','Capacity to Move East Africa'=>'运输东非的强大能力','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics 拥有车队、专业团队和区域经验，可在乌干达及整个东非可靠运输商业货物。',
			'Get a Free Quote'=>'获取免费报价','Explore Services'=>'查看服务','Our Services'=>'我们的服务','Contact Us'=>'联系我们','Road Transport'=>'公路运输','Proudly moving goods for businesses of every size'=>'自豪地为各种规模的企业运输货物',
			'Who we are'=>'关于我们','What we offer'=>'我们的服务','How we can help you move'=>'我们如何帮助您运输','All Services'=>'全部服务','Learn more'=>'了解更多','Why Noki'=>'为何选择 Noki',
			"Built for businesses that can't afford delays"=>'为不能承受延误的企业而打造','Delivering goods reliably'=>'可靠交付货物','Cutting-edge tracking'=>'先进货物追踪','Personalised service'=>'个性化服务',
			'Special highlights'=>'特别亮点','Discover Noki Logistics!'=>'发现 Noki Logistics！','View All News'=>'查看全部新闻','Read more'=>'阅读更多','Success hinges on collaboration'=>'成功源于协作','Your goods, handled like our own'=>'像对待自己的货物一样用心',
			'Door-to-door coordination'=>'门到门协调','One point of contact for the entire journey.'=>'全程一个联系人。','Customs expertise'=>'清关专业能力','Licensed clearing agents who know URA inside-out.'=>'熟悉 URA 流程的持证清关代理。',
			'Transparent pricing'=>'透明定价','Clear quotes upfront — what we say is what you pay.'=>'提前提供清晰报价——所报即所付。','Latest updates'=>'最新动态','From Noki Logistics on LinkedIn'=>'Noki Logistics 的 LinkedIn 动态',
			'Fleet updates, regional operations, company news and insights from our team.'=>'车队更新、区域运营、公司新闻及团队洞察。','View on LinkedIn'=>'在 LinkedIn 查看','Follow Noki Logistics on LinkedIn'=>'在 LinkedIn 关注 Noki Logistics','See our latest fleet updates, regional operations and company news.'=>'查看我们的最新车队动态、区域运营和公司新闻。',
			'Client stories'=>'客户故事','Our values'=>'我们的价值观','Insights'=>'洞察','From our logistics blog'=>'来自我们的物流博客','All Articles'=>'全部文章','Read article'=>'阅读文章','Ready when you are'=>'随时为您服务','Chat on WhatsApp'=>'WhatsApp 咨询',
			'About Noki Logistics'=>'关于 Noki Logistics','Home'=>'首页','About Us'=>'关于我们','Years of excellence'=>'多年卓越服务','Our mission & values'=>'我们的使命与价值观','What drives us'=>'我们的动力','Work With Us'=>'与我们合作',
			"Let's move your business forward"=>'让我们推动您的业务向前','Get in touch today for a free logistics consultation and quote.'=>'立即联系我们，获取免费的物流咨询和报价。','View Services'=>'查看服务',
			"Let's talk about your shipment"=>'让我们聊聊您的货运需求','Visit our office'=>'访问我们的办公室','Call or WhatsApp'=>'电话或 WhatsApp','Working hours'=>'工作时间','Emergency line: 24/7'=>'紧急热线：24/7','Get a free quote'=>'获取免费报价',
			'Our Team'=>'我们的团队','Behind every shipment'=>'每票货物背后的团队','Experienced people who care'=>'经验丰富且用心的团队','Our culture'=>'我们的文化','One team, one promise'=>'一个团队，一个承诺','Join Our Team'=>'加入我们的团队','Work with a team that delivers'=>'与真正能交付的团队合作',
			'Clear, fair pricing'=>'清晰、公平的定价','How pricing works'=>'定价方式','No hidden fees, ever'=>'绝无隐藏费用','Questions'=>'常见问题','Pricing FAQs'=>'价格常见问题','Get your custom quote'=>'获取专属报价','Request a Quote'=>'申请报价','WhatsApp Us'=>'WhatsApp 联系我们',
			'Trusted across East Africa'=>'深受东非客户信赖','Real results, real businesses'=>'真实成果，真实企业','Join hundreds of happy shippers'=>'加入数百家满意客户','Experience logistics you can actually rely on. Get your free quote today.'=>'体验真正可靠的物流服务。立即获取免费报价。',
			'Why businesses choose Noki'=>'企业为何选择 Noki','The Noki difference'=>'Noki 的不同之处','Logistics that works the way you do'=>'契合您业务方式的物流服务','On-time, every time'=>'每次都准时','Dedicated coordinator'=>'专属协调员','Regional reach'=>'区域覆盖','Fully insured cargo'=>'货物全程保险','How it works'=>'服务流程','Simple, from quote to delivery'=>'从报价到交付，简单透明','Start a Shipment'=>'开始发货','See the difference for yourself'=>'亲自体验不同',
			'Logistics Blog'=>'物流博客','No posts yet'=>'暂无文章','Check back soon — we’re working on more logistics insights.'=>'请稍后再来——我们正在准备更多物流洞察。','Our Services'=>'我们的服务','End-to-end logistics'=>'端到端物流','Freight solutions for every need'=>'满足各种需求的货运方案','Not sure which service you need?'=>'不确定需要哪项服务？','Speak to an Expert'=>'咨询专家',
			'Service'=>'服务','Key features'=>'主要特点','Need this service?'=>'需要这项服务？','All services'=>'全部服务','Get a free quote'=>'获取免费报价','Talk to us'=>'联系我们','WhatsApp Chat'=>'WhatsApp 咨询',
			'Stay in the loop'=>'掌握最新动态','News & Events'=>'新闻与活动','Back to News & Events'=>'返回新闻与活动','Latest news'=>'最新新闻','More news coming soon.'=>'更多新闻即将发布。','Need to ship something?'=>'需要运输货物吗？','Recent articles'=>'最新文章','Need a quote?'=>'需要报价？',
			'Page Not Found'=>'页面未找到',"Sorry, the page you're looking for doesn't exist or has been moved."=>'抱歉，您查找的页面不存在或已被移动。','Back to Home'=>'返回首页',
			'Your trusted partner for efficient, reliable freight and supply-chain solutions across Uganda and East Africa. Air, sea and road — delivered with speed and care.'=>'您在乌干达和东非值得信赖的高效、可靠货运与供应链合作伙伴。空运、海运和公路运输——快速且用心地交付。',
			'Get in touch'=>'联系我们','Subscribe for logistics tips & updates.'=>'订阅物流技巧与最新动态。','Your email address'=>'您的电子邮箱','All rights reserved.'=>'版权所有。','Privacy Policy'=>'隐私政策','Terms of Service'=>'服务条款'
		],
		'fr' => [
			'Who We Are'=>'Qui sommes-nous','About Noki'=>'À propos de Noki','A logistics partner you can count on'=>'Un partenaire logistique sur lequel vous pouvez compter','Our story'=>'Notre histoire','Company'=>'Entreprise','Why Choose Us'=>'Pourquoi nous choisir','What sets us apart'=>'Ce qui nous distingue','Our Team'=>'Notre équipe','The people behind Noki'=>'Les personnes derrière Noki','Join Us'=>'Rejoignez-nous','Careers & openings'=>'Carrières et postes','Resources'=>'Ressources','Pricing'=>'Tarifs','Clear, fair rates'=>'Des tarifs clairs et équitables','Testimonials'=>'Témoignages','What clients say'=>'Ce que disent nos clients','FAQ'=>'FAQ','Common questions'=>'Questions fréquentes','Services'=>'Services','Get a quote'=>'Demander un devis','Freight'=>'Fret','Logistics'=>'Logistique','Reliable & insured'=>'Fiable et assuré','Fast & secure'=>'Rapide et sécurisé','Contact'=>'Contact','Call us anytime'=>'Appelez-nous à tout moment','Get a Quote'=>'Demander un devis',
			'Trusted freight partner across East Africa'=>'Partenaire fret de confiance en Afrique de l’Est','Global reach, local expertise'=>'Portée mondiale, expertise locale','Cross-border specialists'=>'Spécialistes du transfrontalier','Our growing road fleet'=>'Notre flotte routière en croissance','Capacity to Move East Africa'=>'La capacité de faire avancer l’Afrique de l’Est','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics dispose de la flotte, des équipes et de l’expérience régionale nécessaires pour transporter de manière fiable des marchandises commerciales en Ouganda et en Afrique de l’Est.',
			'Get a Free Quote'=>'Obtenir un devis gratuit','Explore Services'=>'Découvrir nos services','Our Services'=>'Nos services','Contact Us'=>'Nous contacter','Road Transport'=>'Transport routier','Who we are'=>'Qui sommes-nous','What we offer'=>'Ce que nous proposons','How we can help you move'=>'Comment nous pouvons vous aider à transporter','All Services'=>'Tous les services','Learn more'=>'En savoir plus','Why Noki'=>'Pourquoi Noki',"Built for businesses that can't afford delays"=>'Conçu pour les entreprises qui ne peuvent pas se permettre de retards','Delivering goods reliably'=>'Livraison fiable des marchandises','Cutting-edge tracking'=>'Suivi de pointe','Personalised service'=>'Service personnalisé',
			'Special highlights'=>'À la une','Discover Noki Logistics!'=>'Découvrez Noki Logistics !','View All News'=>'Voir toutes les actualités','Read more'=>'Lire la suite','Transparent pricing'=>'Tarification transparente','Latest updates'=>'Dernières nouvelles','From Noki Logistics on LinkedIn'=>'Noki Logistics sur LinkedIn','View on LinkedIn'=>'Voir sur LinkedIn','Follow Noki Logistics on LinkedIn'=>'Suivre Noki Logistics sur LinkedIn','Client stories'=>'Témoignages clients','Our values'=>'Nos valeurs','Insights'=>'Conseils','From our logistics blog'=>'Sur notre blog logistique','All Articles'=>'Tous les articles','Read article'=>'Lire l’article','Ready when you are'=>'Prêts quand vous l’êtes','Chat on WhatsApp'=>'Discuter sur WhatsApp',
			'About Noki Logistics'=>'À propos de Noki Logistics','Home'=>'Accueil','About Us'=>'À propos','Years of excellence'=>'Années d’excellence','Our mission & values'=>'Notre mission et nos valeurs','What drives us'=>'Ce qui nous motive','Work With Us'=>'Travaillez avec nous',"Let's move your business forward"=>'Faisons avancer votre entreprise','View Services'=>'Voir les services',
			"Let's talk about your shipment"=>'Parlons de votre expédition','Visit our office'=>'Visitez nos bureaux','Call or WhatsApp'=>'Appelez ou WhatsApp','Working hours'=>'Horaires','Emergency line: 24/7'=>'Ligne d’urgence : 24/7','Get a free quote'=>'Obtenir un devis gratuit',
			'Behind every shipment'=>'Derrière chaque expédition','Experienced people who care'=>'Des professionnels expérimentés et attentifs','Our culture'=>'Notre culture','One team, one promise'=>'Une équipe, une promesse','Join Our Team'=>'Rejoignez notre équipe','Work with a team that delivers'=>'Travaillez avec une équipe qui tient ses engagements',
			'How pricing works'=>'Comment fonctionnent nos tarifs','No hidden fees, ever'=>'Aucun frais caché','Questions'=>'Questions','Pricing FAQs'=>'FAQ sur les tarifs','Get your custom quote'=>'Obtenez votre devis personnalisé','Request a Quote'=>'Demander un devis','WhatsApp Us'=>'Nous écrire sur WhatsApp',
			'Trusted across East Africa'=>'La confiance partout en Afrique de l’Est','Real results, real businesses'=>'Des résultats réels pour de vraies entreprises','Join hundreds of happy shippers'=>'Rejoignez des centaines de clients satisfaits','Why businesses choose Noki'=>'Pourquoi les entreprises choisissent Noki','The Noki difference'=>'La différence Noki','Logistics that works the way you do'=>'Une logistique adaptée à votre façon de travailler','On-time, every time'=>'Toujours à l’heure','Dedicated coordinator'=>'Coordinateur dédié','Regional reach'=>'Couverture régionale','Fully insured cargo'=>'Marchandises entièrement assurées','How it works'=>'Comment ça marche','Simple, from quote to delivery'=>'Simple, du devis à la livraison','Start a Shipment'=>'Démarrer une expédition','See the difference for yourself'=>'Voyez la différence par vous-même',
			'Logistics Blog'=>'Blog logistique','No posts yet'=>'Aucun article pour le moment','Our Services'=>'Nos services','End-to-end logistics'=>'Logistique de bout en bout','Freight solutions for every need'=>'Des solutions de fret pour chaque besoin','Not sure which service you need?'=>'Vous ne savez pas quel service choisir ?','Speak to an Expert'=>'Parler à un expert','Service'=>'Service','Key features'=>'Caractéristiques principales','Need this service?'=>'Besoin de ce service ?','All services'=>'Tous les services','Talk to us'=>'Parlez-nous','WhatsApp Chat'=>'Chat WhatsApp','Stay in the loop'=>'Restez informé','News & Events'=>'Actualités et événements','Back to News & Events'=>'Retour aux actualités','Latest news'=>'Dernières actualités','More news coming soon.'=>'Plus d’actualités bientôt.','Need to ship something?'=>'Vous avez quelque chose à expédier ?','Recent articles'=>'Articles récents','Need a quote?'=>'Besoin d’un devis ?',
			'Page Not Found'=>'Page introuvable',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Désolé, la page que vous recherchez n’existe pas ou a été déplacée.','Back to Home'=>'Retour à l’accueil','Get in touch'=>'Nous contacter','Subscribe for logistics tips & updates.'=>'Abonnez-vous à nos conseils et actualités logistiques.','Your email address'=>'Votre adresse e-mail','All rights reserved.'=>'Tous droits réservés.','Privacy Policy'=>'Politique de confidentialité','Terms of Service'=>'Conditions d’utilisation'
		],
		'de' => [
			'Who We Are'=>'Über uns','About Noki'=>'Über Noki','A logistics partner you can count on'=>'Ein Logistikpartner, auf den Sie zählen können','Our story'=>'Unsere Geschichte','Company'=>'Unternehmen','Why Choose Us'=>'Warum Noki','What sets us apart'=>'Was uns auszeichnet','Our Team'=>'Unser Team','The people behind Noki'=>'Die Menschen hinter Noki','Join Us'=>'Karriere','Careers & openings'=>'Karriere & Stellen','Resources'=>'Ressourcen','Pricing'=>'Preise','Clear, fair rates'=>'Klare, faire Preise','Testimonials'=>'Kundenstimmen','What clients say'=>'Was unsere Kunden sagen','FAQ'=>'FAQ','Common questions'=>'Häufige Fragen','Services'=>'Leistungen','Get a quote'=>'Angebot anfordern','Freight'=>'Fracht','Logistics'=>'Logistik','Reliable & insured'=>'Zuverlässig & versichert','Fast & secure'=>'Schnell & sicher','Contact'=>'Kontakt','Call us anytime'=>'Rufen Sie uns jederzeit an','Get a Quote'=>'Angebot anfordern',
			'Trusted freight partner across East Africa'=>'Verlässlicher Frachtpartner in Ostafrika','Global reach, local expertise'=>'Globale Reichweite, lokale Expertise','Cross-border specialists'=>'Spezialisten für grenzüberschreitende Transporte','Our growing road fleet'=>'Unsere wachsende Lkw-Flotte','Capacity to Move East Africa'=>'Kapazität, Ostafrika zu bewegen','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics verfügt über die Flotte, das Team und die regionale Erfahrung, um kommerzielle Fracht zuverlässig in Uganda und Ostafrika zu transportieren.',
			'Get a Free Quote'=>'Kostenloses Angebot','Explore Services'=>'Leistungen entdecken','Our Services'=>'Unsere Leistungen','Contact Us'=>'Kontaktieren Sie uns','Road Transport'=>'Straßentransport','Who we are'=>'Über uns','What we offer'=>'Was wir bieten','How we can help you move'=>'Wie wir Ihre Fracht bewegen','All Services'=>'Alle Leistungen','Learn more'=>'Mehr erfahren','Why Noki'=>'Warum Noki',"Built for businesses that can't afford delays"=>'Für Unternehmen, die sich Verzögerungen nicht leisten können','Delivering goods reliably'=>'Zuverlässige Lieferung','Cutting-edge tracking'=>'Modernes Tracking','Personalised service'=>'Persönlicher Service',
			'Special highlights'=>'Highlights','Discover Noki Logistics!'=>'Entdecken Sie Noki Logistics!','View All News'=>'Alle Neuigkeiten','Read more'=>'Weiterlesen','Transparent pricing'=>'Transparente Preise','Latest updates'=>'Neueste Updates','From Noki Logistics on LinkedIn'=>'Noki Logistics auf LinkedIn','View on LinkedIn'=>'Auf LinkedIn ansehen','Follow Noki Logistics on LinkedIn'=>'Noki Logistics auf LinkedIn folgen','Client stories'=>'Kundengeschichten','Our values'=>'Unsere Werte','Insights'=>'Einblicke','From our logistics blog'=>'Aus unserem Logistik-Blog','All Articles'=>'Alle Artikel','Read article'=>'Artikel lesen','Ready when you are'=>'Bereit, wenn Sie es sind','Chat on WhatsApp'=>'Auf WhatsApp chatten',
			'About Noki Logistics'=>'Über Noki Logistics','Home'=>'Startseite','About Us'=>'Über uns','Years of excellence'=>'Jahre Exzellenz','Our mission & values'=>'Unsere Mission & Werte','What drives us'=>'Was uns antreibt','Work With Us'=>'Mit uns arbeiten',"Let's move your business forward"=>'Bringen wir Ihr Geschäft voran','View Services'=>'Leistungen ansehen',
			"Let's talk about your shipment"=>'Sprechen wir über Ihre Sendung','Visit our office'=>'Besuchen Sie unser Büro','Call or WhatsApp'=>'Anrufen oder WhatsApp','Working hours'=>'Öffnungszeiten','Emergency line: 24/7'=>'Notfallnummer: 24/7','Get a free quote'=>'Kostenloses Angebot',
			'Behind every shipment'=>'Hinter jeder Sendung','Experienced people who care'=>'Erfahrene Menschen, die sich kümmern','Our culture'=>'Unsere Kultur','One team, one promise'=>'Ein Team, ein Versprechen','Join Our Team'=>'Unserem Team beitreten','Work with a team that delivers'=>'Arbeiten Sie mit einem Team, das liefert',
			'How pricing works'=>'So funktioniert die Preisgestaltung','No hidden fees, ever'=>'Keine versteckten Gebühren','Questions'=>'Fragen','Pricing FAQs'=>'Preis-FAQ','Get your custom quote'=>'Ihr individuelles Angebot','Request a Quote'=>'Angebot anfordern','WhatsApp Us'=>'WhatsApp',
			'Trusted across East Africa'=>'Vertrauen in ganz Ostafrika','Real results, real businesses'=>'Echte Ergebnisse, echte Unternehmen','Join hundreds of happy shippers'=>'Werden Sie Teil hunderter zufriedener Kunden','Why businesses choose Noki'=>'Warum Unternehmen Noki wählen','The Noki difference'=>'Der Noki-Unterschied','Logistics that works the way you do'=>'Logistik, die zu Ihrem Geschäft passt','On-time, every time'=>'Immer pünktlich','Dedicated coordinator'=>'Persönlicher Koordinator','Regional reach'=>'Regionale Reichweite','Fully insured cargo'=>'Voll versicherte Fracht','How it works'=>'So funktioniert es','Simple, from quote to delivery'=>'Einfach vom Angebot bis zur Lieferung','Start a Shipment'=>'Sendung starten','See the difference for yourself'=>'Erleben Sie den Unterschied',
			'Logistics Blog'=>'Logistik-Blog','No posts yet'=>'Noch keine Beiträge','Our Services'=>'Unsere Leistungen','End-to-end logistics'=>'End-to-End-Logistik','Freight solutions for every need'=>'Frachtlösungen für jeden Bedarf','Not sure which service you need?'=>'Unsicher, welchen Service Sie benötigen?','Speak to an Expert'=>'Mit einem Experten sprechen','Service'=>'Leistung','Key features'=>'Wichtige Merkmale','Need this service?'=>'Benötigen Sie diesen Service?','All services'=>'Alle Leistungen','Talk to us'=>'Sprechen Sie mit uns','WhatsApp Chat'=>'WhatsApp-Chat','Stay in the loop'=>'Bleiben Sie informiert','News & Events'=>'News & Events','Back to News & Events'=>'Zurück zu News & Events','Latest news'=>'Neueste Nachrichten','More news coming soon.'=>'Weitere Nachrichten folgen.','Need to ship something?'=>'Müssen Sie etwas versenden?','Recent articles'=>'Aktuelle Artikel','Need a quote?'=>'Benötigen Sie ein Angebot?',
			'Page Not Found'=>'Seite nicht gefunden',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Die gesuchte Seite existiert nicht oder wurde verschoben.','Back to Home'=>'Zur Startseite','Get in touch'=>'Kontakt aufnehmen','Subscribe for logistics tips & updates.'=>'Abonnieren Sie Logistik-Tipps und Updates.','Your email address'=>'Ihre E-Mail-Adresse','All rights reserved.'=>'Alle Rechte vorbehalten.','Privacy Policy'=>'Datenschutz','Terms of Service'=>'Nutzungsbedingungen'
		],
		'es' => [
			'Who We Are'=>'Quiénes somos','About Noki'=>'Sobre Noki','A logistics partner you can count on'=>'Un socio logístico en quien puede confiar','Our story'=>'Nuestra historia','Company'=>'Empresa','Why Choose Us'=>'Por qué elegirnos','What sets us apart'=>'Lo que nos diferencia','Our Team'=>'Nuestro equipo','The people behind Noki'=>'Las personas detrás de Noki','Join Us'=>'Únete a nosotros','Careers & openings'=>'Carreras y vacantes','Resources'=>'Recursos','Pricing'=>'Precios','Clear, fair rates'=>'Tarifas claras y justas','Testimonials'=>'Testimonios','What clients say'=>'Lo que dicen nuestros clientes','FAQ'=>'Preguntas frecuentes','Common questions'=>'Preguntas frecuentes','Services'=>'Servicios','Get a quote'=>'Solicitar cotización','Freight'=>'Carga','Logistics'=>'Logística','Reliable & insured'=>'Confiable y asegurado','Fast & secure'=>'Rápido y seguro','Contact'=>'Contacto','Call us anytime'=>'Llámenos cuando quiera','Get a Quote'=>'Solicitar cotización',
			'Trusted freight partner across East Africa'=>'Socio de carga confiable en África Oriental','Global reach, local expertise'=>'Alcance global, experiencia local','Cross-border specialists'=>'Especialistas transfronterizos','Our growing road fleet'=>'Nuestra creciente flota terrestre','Capacity to Move East Africa'=>'Capacidad para mover África Oriental','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics cuenta con la flota, el personal y la experiencia regional para mover carga comercial de forma confiable por Uganda y África Oriental.',
			'Get a Free Quote'=>'Obtener cotización gratis','Explore Services'=>'Explorar servicios','Our Services'=>'Nuestros servicios','Contact Us'=>'Contáctenos','Road Transport'=>'Transporte terrestre','Who we are'=>'Quiénes somos','What we offer'=>'Lo que ofrecemos','How we can help you move'=>'Cómo podemos ayudarle a mover su carga','All Services'=>'Todos los servicios','Learn more'=>'Más información','Why Noki'=>'Por qué Noki',"Built for businesses that can't afford delays"=>'Diseñado para empresas que no pueden permitirse retrasos','Delivering goods reliably'=>'Entregas confiables','Cutting-edge tracking'=>'Seguimiento avanzado','Personalised service'=>'Servicio personalizado',
			'Special highlights'=>'Destacados','Discover Noki Logistics!'=>'¡Descubra Noki Logistics!','View All News'=>'Ver todas las noticias','Read more'=>'Leer más','Transparent pricing'=>'Precios transparentes','Latest updates'=>'Últimas novedades','From Noki Logistics on LinkedIn'=>'Noki Logistics en LinkedIn','View on LinkedIn'=>'Ver en LinkedIn','Follow Noki Logistics on LinkedIn'=>'Seguir a Noki Logistics en LinkedIn','Client stories'=>'Historias de clientes','Our values'=>'Nuestros valores','Insights'=>'Ideas','From our logistics blog'=>'Desde nuestro blog de logística','All Articles'=>'Todos los artículos','Read article'=>'Leer artículo','Ready when you are'=>'Listos cuando usted lo esté','Chat on WhatsApp'=>'Chatear por WhatsApp',
			'About Noki Logistics'=>'Sobre Noki Logistics','Home'=>'Inicio','About Us'=>'Sobre nosotros','Years of excellence'=>'Años de excelencia','Our mission & values'=>'Nuestra misión y valores','What drives us'=>'Lo que nos impulsa','Work With Us'=>'Trabaje con nosotros',"Let's move your business forward"=>'Hagamos avanzar su negocio','View Services'=>'Ver servicios',
			"Let's talk about your shipment"=>'Hablemos de su envío','Visit our office'=>'Visite nuestra oficina','Call or WhatsApp'=>'Llame o escriba por WhatsApp','Working hours'=>'Horario','Emergency line: 24/7'=>'Línea de emergencia: 24/7','Get a free quote'=>'Obtener cotización gratis',
			'Behind every shipment'=>'Detrás de cada envío','Experienced people who care'=>'Personas con experiencia que se preocupan','Our culture'=>'Nuestra cultura','One team, one promise'=>'Un equipo, una promesa','Join Our Team'=>'Únase a nuestro equipo','Work with a team that delivers'=>'Trabaje con un equipo que cumple',
			'How pricing works'=>'Cómo funcionan los precios','No hidden fees, ever'=>'Sin cargos ocultos','Questions'=>'Preguntas','Pricing FAQs'=>'Preguntas sobre precios','Get your custom quote'=>'Obtenga su cotización personalizada','Request a Quote'=>'Solicitar cotización','WhatsApp Us'=>'WhatsApp',
			'Trusted across East Africa'=>'Confianza en toda África Oriental','Real results, real businesses'=>'Resultados reales, empresas reales','Join hundreds of happy shippers'=>'Únase a cientos de clientes satisfechos','Why businesses choose Noki'=>'Por qué las empresas eligen Noki','The Noki difference'=>'La diferencia Noki','Logistics that works the way you do'=>'Logística que funciona a su manera','On-time, every time'=>'Siempre a tiempo','Dedicated coordinator'=>'Coordinador dedicado','Regional reach'=>'Alcance regional','Fully insured cargo'=>'Carga totalmente asegurada','How it works'=>'Cómo funciona','Simple, from quote to delivery'=>'Simple, desde la cotización hasta la entrega','Start a Shipment'=>'Iniciar un envío','See the difference for yourself'=>'Compruebe la diferencia',
			'Logistics Blog'=>'Blog de logística','No posts yet'=>'Aún no hay artículos','Our Services'=>'Nuestros servicios','End-to-end logistics'=>'Logística de extremo a extremo','Freight solutions for every need'=>'Soluciones de carga para cada necesidad','Not sure which service you need?'=>'¿No sabe qué servicio necesita?','Speak to an Expert'=>'Hablar con un experto','Service'=>'Servicio','Key features'=>'Características principales','Need this service?'=>'¿Necesita este servicio?','All services'=>'Todos los servicios','Talk to us'=>'Hable con nosotros','WhatsApp Chat'=>'Chat de WhatsApp','Stay in the loop'=>'Manténgase informado','News & Events'=>'Noticias y eventos','Back to News & Events'=>'Volver a noticias y eventos','Latest news'=>'Últimas noticias','More news coming soon.'=>'Más noticias próximamente.','Need to ship something?'=>'¿Necesita enviar algo?','Recent articles'=>'Artículos recientes','Need a quote?'=>'¿Necesita una cotización?',
			'Page Not Found'=>'Página no encontrada',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Lo sentimos, la página que busca no existe o ha sido movida.','Back to Home'=>'Volver al inicio','Get in touch'=>'Contáctenos','Subscribe for logistics tips & updates.'=>'Suscríbase a consejos y novedades de logística.','Your email address'=>'Su correo electrónico','All rights reserved.'=>'Todos los derechos reservados.','Privacy Policy'=>'Política de privacidad','Terms of Service'=>'Términos del servicio'
		],
		'pl' => [
			'Who We Are'=>'O nas','About Noki'=>'O Noki','A logistics partner you can count on'=>'Partner logistyczny, na którym możesz polegać','Our story'=>'Nasza historia','Company'=>'Firma','Why Choose Us'=>'Dlaczego my','What sets us apart'=>'Co nas wyróżnia','Our Team'=>'Nasz zespół','The people behind Noki'=>'Ludzie tworzący Noki','Join Us'=>'Dołącz do nas','Careers & openings'=>'Kariera i oferty pracy','Resources'=>'Materiały','Pricing'=>'Cennik','Clear, fair rates'=>'Jasne i uczciwe stawki','Testimonials'=>'Opinie klientów','What clients say'=>'Co mówią klienci','FAQ'=>'FAQ','Common questions'=>'Częste pytania','Services'=>'Usługi','Get a quote'=>'Poproś o wycenę','Freight'=>'Transport','Logistics'=>'Logistyka','Reliable & insured'=>'Niezawodnie i z ubezpieczeniem','Fast & secure'=>'Szybko i bezpiecznie','Contact'=>'Kontakt','Call us anytime'=>'Zadzwoń do nas','Get a Quote'=>'Poproś o wycenę',
			'Trusted freight partner across East Africa'=>'Zaufany partner transportowy w Afryce Wschodniej','Global reach, local expertise'=>'Globalny zasięg, lokalne doświadczenie','Cross-border specialists'=>'Specjaliści od transportu transgranicznego','Our growing road fleet'=>'Nasza rosnąca flota drogowa','Capacity to Move East Africa'=>'Potencjał do obsługi Afryki Wschodniej','Noki Logistics has the fleet, people and regional experience to move commercial cargo reliably across Uganda and East Africa.'=>'Noki Logistics ma flotę, zespół i doświadczenie regionalne potrzebne do niezawodnego przewozu ładunków komercyjnych w Ugandzie i Afryce Wschodniej.',
			'Get a Free Quote'=>'Bezpłatna wycena','Explore Services'=>'Poznaj usługi','Our Services'=>'Nasze usługi','Contact Us'=>'Skontaktuj się','Road Transport'=>'Transport drogowy','Who we are'=>'O nas','What we offer'=>'Co oferujemy','How we can help you move'=>'Jak możemy pomóc w transporcie','All Services'=>'Wszystkie usługi','Learn more'=>'Dowiedz się więcej','Why Noki'=>'Dlaczego Noki',"Built for businesses that can't afford delays"=>'Dla firm, które nie mogą pozwolić sobie na opóźnienia','Delivering goods reliably'=>'Niezawodne dostawy','Cutting-edge tracking'=>'Nowoczesne śledzenie','Personalised service'=>'Spersonalizowana obsługa',
			'Special highlights'=>'Wyróżnione','Discover Noki Logistics!'=>'Poznaj Noki Logistics!','View All News'=>'Wszystkie aktualności','Read more'=>'Czytaj więcej','Transparent pricing'=>'Przejrzyste ceny','Latest updates'=>'Najnowsze informacje','From Noki Logistics on LinkedIn'=>'Noki Logistics na LinkedIn','View on LinkedIn'=>'Zobacz na LinkedIn','Follow Noki Logistics on LinkedIn'=>'Obserwuj Noki Logistics na LinkedIn','Client stories'=>'Historie klientów','Our values'=>'Nasze wartości','Insights'=>'Wiedza','From our logistics blog'=>'Z naszego bloga logistycznego','All Articles'=>'Wszystkie artykuły','Read article'=>'Czytaj artykuł','Ready when you are'=>'Gotowi, kiedy Ty jesteś','Chat on WhatsApp'=>'Napisz na WhatsApp',
			'About Noki Logistics'=>'O Noki Logistics','Home'=>'Strona główna','About Us'=>'O nas','Years of excellence'=>'Lata doskonałości','Our mission & values'=>'Nasza misja i wartości','What drives us'=>'Co nas napędza','Work With Us'=>'Współpracuj z nami',"Let's move your business forward"=>'Rozwijajmy Twój biznes','View Services'=>'Zobacz usługi',
			"Let's talk about your shipment"=>'Porozmawiajmy o Twojej przesyłce','Visit our office'=>'Odwiedź nasze biuro','Call or WhatsApp'=>'Zadzwoń lub WhatsApp','Working hours'=>'Godziny pracy','Emergency line: 24/7'=>'Linia alarmowa: 24/7','Get a free quote'=>'Bezpłatna wycena',
			'Behind every shipment'=>'Za każdą przesyłką','Experienced people who care'=>'Doświadczeni ludzie, którym zależy','Our culture'=>'Nasza kultura','One team, one promise'=>'Jeden zespół, jedna obietnica','Join Our Team'=>'Dołącz do zespołu','Work with a team that delivers'=>'Pracuj z zespołem, który dowozi wyniki',
			'How pricing works'=>'Jak działa wycena','No hidden fees, ever'=>'Bez ukrytych opłat','Questions'=>'Pytania','Pricing FAQs'=>'FAQ dotyczące cen','Get your custom quote'=>'Uzyskaj indywidualną wycenę','Request a Quote'=>'Poproś o wycenę','WhatsApp Us'=>'WhatsApp',
			'Trusted across East Africa'=>'Zaufanie w całej Afryce Wschodniej','Real results, real businesses'=>'Prawdziwe wyniki, prawdziwe firmy','Join hundreds of happy shippers'=>'Dołącz do setek zadowolonych klientów','Why businesses choose Noki'=>'Dlaczego firmy wybierają Noki','The Noki difference'=>'Różnica Noki','Logistics that works the way you do'=>'Logistyka dopasowana do Twojego biznesu','On-time, every time'=>'Zawsze na czas','Dedicated coordinator'=>'Dedykowany koordynator','Regional reach'=>'Zasięg regionalny','Fully insured cargo'=>'Pełne ubezpieczenie ładunku','How it works'=>'Jak to działa','Simple, from quote to delivery'=>'Prosto od wyceny do dostawy','Start a Shipment'=>'Rozpocznij wysyłkę','See the difference for yourself'=>'Zobacz różnicę',
			'Logistics Blog'=>'Blog logistyczny','No posts yet'=>'Brak artykułów','Our Services'=>'Nasze usługi','End-to-end logistics'=>'Logistyka end-to-end','Freight solutions for every need'=>'Rozwiązania transportowe na każdą potrzebę','Not sure which service you need?'=>'Nie wiesz, której usługi potrzebujesz?','Speak to an Expert'=>'Porozmawiaj z ekspertem','Service'=>'Usługa','Key features'=>'Najważniejsze cechy','Need this service?'=>'Potrzebujesz tej usługi?','All services'=>'Wszystkie usługi','Talk to us'=>'Porozmawiaj z nami','WhatsApp Chat'=>'Czat WhatsApp','Stay in the loop'=>'Bądź na bieżąco','News & Events'=>'Aktualności i wydarzenia','Back to News & Events'=>'Wróć do aktualności','Latest news'=>'Najnowsze wiadomości','More news coming soon.'=>'Więcej wiadomości wkrótce.','Need to ship something?'=>'Potrzebujesz coś wysłać?','Recent articles'=>'Najnowsze artykuły','Need a quote?'=>'Potrzebujesz wyceny?',
			'Page Not Found'=>'Nie znaleziono strony',"Sorry, the page you're looking for doesn't exist or has been moved."=>'Przepraszamy, szukana strona nie istnieje lub została przeniesiona.','Back to Home'=>'Wróć na stronę główną','Get in touch'=>'Skontaktuj się','Subscribe for logistics tips & updates.'=>'Zapisz się po porady logistyczne i aktualności.','Your email address'=>'Twój adres e-mail','All rights reserved.'=>'Wszelkie prawa zastrzeżone.','Privacy Policy'=>'Polityka prywatności','Terms of Service'=>'Warunki korzystania'
		],
	];
	$auto = get_option( 'noki_ui_auto_translations', [] );
	if ( is_array( $auto ) ) {
		foreach ( $auto as $lang => $map ) {
			if ( is_array( $map ) ) {
				$manual[ $lang ] = array_merge( $map, $manual[ $lang ] ?? [] );
			}
		}
	}
	return $manual;
}

function noki_translate_fixed_html( $html ) {
	if ( is_admin() || ! function_exists( 'pll_current_language' ) ) return $html;
	$lang = pll_current_language( 'slug' );
	if ( ! $lang || 'en' === $lang ) return $html;

	$all = noki_ui_translations();
	if ( empty( $all[ $lang ] ) || ! is_string( $html ) || '' === $html ) return $html;

	/*
	 * IMPORTANT: translate visible text only.
	 * Running strtr() over the complete HTML can alter stylesheet/script URLs,
	 * class names and attributes (for example words such as "about" or
	 * "contact"), which makes translated pages render as unstyled/plain text.
	 * Script/style blocks and all HTML tags are preserved byte-for-byte.
	 */
	$parts = preg_split(
		'~(<script\\b[^>]*>.*?</script>|<style\\b[^>]*>.*?</style>|<noscript\\b[^>]*>.*?</noscript>|<[^>]+>)~is',
		$html,
		-1,
		PREG_SPLIT_DELIM_CAPTURE
	);

	if ( false === $parts ) return $html;

	foreach ( $parts as $i => $part ) {
		if ( '' === $part || '<' === $part[0] ) continue;
		$parts[ $i ] = strtr( $part, $all[ $lang ] );
	}

	return implode( '', $parts );
}

function noki_start_translation_buffer() {
	if ( is_admin() || wp_doing_ajax() || wp_doing_cron() ) return;
	if ( function_exists( 'pll_current_language' ) && 'en' !== pll_current_language( 'slug' ) ) {
		ob_start( 'noki_translate_fixed_html' );
	}
}
add_action( 'template_redirect', 'noki_start_translation_buffer', 0 );
